import type { Config } from '@puckeditor/core';
import {
    HeadingBlockConfig,
    ParagraphBlockConfig,
    StatCardBlockConfig,
    BannerBlockConfig,
    ButtonBlockConfig,
    ImageBlockConfig,
    SpacerBlockConfig,
    DividerBlockConfig,
    ListBlockConfig,
    ChipListBlockConfig,
    TwoColumnBlockConfig,
    SidebarLayoutBlockConfig,
    NavMenuBlockConfig,
    SideMenuBlockConfig,
    MenuItemBlockConfig,
    BreadcrumbBlockConfig,
    AccordionBlockConfig,
    PageHeaderBlockConfig,
    DataTableBlockConfig,
    KpiRowBlockConfig,
    TimelineBlockConfig,
    TabsLayoutBlockConfig,
    CardGridBlockConfig,
    QuoteBlockConfig,
    FooterBlockConfig,
    DynamicMenuBlockConfig,
    SearchBarBlockConfig,
} from './blocks';

export const PUCK_CONFIG: Config = {
    components: {
        HeadingBlock: HeadingBlockConfig,
        ParagraphBlock: ParagraphBlockConfig,
        StatCardBlock: StatCardBlockConfig,
        BannerBlock: BannerBlockConfig,
        ButtonBlock: ButtonBlockConfig,
        ImageBlock: ImageBlockConfig,
        SpacerBlock: SpacerBlockConfig,
        DividerBlock: DividerBlockConfig,
        ListBlock: ListBlockConfig,
        ChipListBlock: ChipListBlockConfig,
        TwoColumnBlock: TwoColumnBlockConfig,
        SidebarLayout: SidebarLayoutBlockConfig,
        NavMenu: NavMenuBlockConfig,
        SideMenu: SideMenuBlockConfig,
        MenuItem: MenuItemBlockConfig,
        Breadcrumb: BreadcrumbBlockConfig,
        Accordion: AccordionBlockConfig,
        PageHeader: PageHeaderBlockConfig,
        DataTable: DataTableBlockConfig,
        KpiRow: KpiRowBlockConfig,
        Timeline: TimelineBlockConfig,
        TabsLayout: TabsLayoutBlockConfig,
        CardGrid: CardGridBlockConfig,
        Quote: QuoteBlockConfig,
        Footer: FooterBlockConfig,
        DynamicMenu: DynamicMenuBlockConfig,
        SearchBar: SearchBarBlockConfig,
    },
} as unknown as Config;
