// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Catalog.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace protos {
  public static partial class CatalogService
  {
    static readonly string __ServiceName = "catalog.CatalogService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.CatalogListRequest> __Marshaller_catalog_CatalogListRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.CatalogListRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.CatalogListResponse> __Marshaller_catalog_CatalogListResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.CatalogListResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.CatalogRequest> __Marshaller_catalog_CatalogRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.CatalogRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.CatalogResponse> __Marshaller_catalog_CatalogResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.CatalogResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.CatalogDeleteResponse> __Marshaller_catalog_CatalogDeleteResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.CatalogDeleteResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.SaveCatalogRequest> __Marshaller_catalog_SaveCatalogRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.SaveCatalogRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.SaveCatalogResponse> __Marshaller_catalog_SaveCatalogResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.SaveCatalogResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.CatalogTreeListRequest> __Marshaller_catalog_CatalogTreeListRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.CatalogTreeListRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.CatalogTreeListResponse> __Marshaller_catalog_CatalogTreeListResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.CatalogTreeListResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.CatalogTreeRequest> __Marshaller_catalog_CatalogTreeRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.CatalogTreeRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.CatalogTreeResponse> __Marshaller_catalog_CatalogTreeResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.CatalogTreeResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.CatalogTreeDeleteResponse> __Marshaller_catalog_CatalogTreeDeleteResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.CatalogTreeDeleteResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.SaveCatalogTreeRequest> __Marshaller_catalog_SaveCatalogTreeRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.SaveCatalogTreeRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.SaveCatalogTreeResponse> __Marshaller_catalog_SaveCatalogTreeResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.SaveCatalogTreeResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.ReorderCatalogTreeRequest> __Marshaller_catalog_ReorderCatalogTreeRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.ReorderCatalogTreeRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.UploadCatalogFromExcelRequest> __Marshaller_catalog_UploadCatalogFromExcelRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.UploadCatalogFromExcelRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.UploadCatalogFromExcelResponse> __Marshaller_catalog_UploadCatalogFromExcelResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.UploadCatalogFromExcelResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.SaveCatalogFromExcelRequest> __Marshaller_catalog_SaveCatalogFromExcelRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.SaveCatalogFromExcelRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.SaveCatalogFromExcelResponse> __Marshaller_catalog_SaveCatalogFromExcelResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.SaveCatalogFromExcelResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.CatalogListRequest, global::protos.CatalogListResponse> __Method_GetListCatalog = new grpc::Method<global::protos.CatalogListRequest, global::protos.CatalogListResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetListCatalog",
        __Marshaller_catalog_CatalogListRequest,
        __Marshaller_catalog_CatalogListResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.CatalogRequest, global::protos.CatalogResponse> __Method_GetCatalog = new grpc::Method<global::protos.CatalogRequest, global::protos.CatalogResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetCatalog",
        __Marshaller_catalog_CatalogRequest,
        __Marshaller_catalog_CatalogResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.CatalogRequest, global::protos.CatalogDeleteResponse> __Method_DeleteCatalog = new grpc::Method<global::protos.CatalogRequest, global::protos.CatalogDeleteResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteCatalog",
        __Marshaller_catalog_CatalogRequest,
        __Marshaller_catalog_CatalogDeleteResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.SaveCatalogRequest, global::protos.SaveCatalogResponse> __Method_SaveCatalog = new grpc::Method<global::protos.SaveCatalogRequest, global::protos.SaveCatalogResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SaveCatalog",
        __Marshaller_catalog_SaveCatalogRequest,
        __Marshaller_catalog_SaveCatalogResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.CatalogListRequest, global::protos.CatalogResponse> __Method_GetLastCatalog = new grpc::Method<global::protos.CatalogListRequest, global::protos.CatalogResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetLastCatalog",
        __Marshaller_catalog_CatalogListRequest,
        __Marshaller_catalog_CatalogResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.CatalogListRequest, global::protos.CatalogResponse> __Method_GetMaxCatalog = new grpc::Method<global::protos.CatalogListRequest, global::protos.CatalogResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetMaxCatalog",
        __Marshaller_catalog_CatalogListRequest,
        __Marshaller_catalog_CatalogResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.CatalogTreeListRequest, global::protos.CatalogTreeListResponse> __Method_GetListCatalogTree = new grpc::Method<global::protos.CatalogTreeListRequest, global::protos.CatalogTreeListResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetListCatalogTree",
        __Marshaller_catalog_CatalogTreeListRequest,
        __Marshaller_catalog_CatalogTreeListResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.CatalogTreeRequest, global::protos.CatalogTreeResponse> __Method_GetCatalogTree = new grpc::Method<global::protos.CatalogTreeRequest, global::protos.CatalogTreeResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetCatalogTree",
        __Marshaller_catalog_CatalogTreeRequest,
        __Marshaller_catalog_CatalogTreeResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.CatalogTreeRequest, global::protos.CatalogTreeDeleteResponse> __Method_DeleteCatalogTree = new grpc::Method<global::protos.CatalogTreeRequest, global::protos.CatalogTreeDeleteResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteCatalogTree",
        __Marshaller_catalog_CatalogTreeRequest,
        __Marshaller_catalog_CatalogTreeDeleteResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.SaveCatalogTreeRequest, global::protos.SaveCatalogTreeResponse> __Method_SaveCatalogTree = new grpc::Method<global::protos.SaveCatalogTreeRequest, global::protos.SaveCatalogTreeResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SaveCatalogTree",
        __Marshaller_catalog_SaveCatalogTreeRequest,
        __Marshaller_catalog_SaveCatalogTreeResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.CatalogTreeListRequest, global::protos.CatalogTreeResponse> __Method_GetLastCatalogTree = new grpc::Method<global::protos.CatalogTreeListRequest, global::protos.CatalogTreeResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetLastCatalogTree",
        __Marshaller_catalog_CatalogTreeListRequest,
        __Marshaller_catalog_CatalogTreeResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.CatalogTreeListRequest, global::protos.CatalogTreeResponse> __Method_GetMaxCatalogTree = new grpc::Method<global::protos.CatalogTreeListRequest, global::protos.CatalogTreeResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetMaxCatalogTree",
        __Marshaller_catalog_CatalogTreeListRequest,
        __Marshaller_catalog_CatalogTreeResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.ReorderCatalogTreeRequest, global::protos.SaveCatalogTreeResponse> __Method_ReorderCatalogTree = new grpc::Method<global::protos.ReorderCatalogTreeRequest, global::protos.SaveCatalogTreeResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ReorderCatalogTree",
        __Marshaller_catalog_ReorderCatalogTreeRequest,
        __Marshaller_catalog_SaveCatalogTreeResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.UploadCatalogFromExcelRequest, global::protos.UploadCatalogFromExcelResponse> __Method_UploadCatalogFromExcel = new grpc::Method<global::protos.UploadCatalogFromExcelRequest, global::protos.UploadCatalogFromExcelResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UploadCatalogFromExcel",
        __Marshaller_catalog_UploadCatalogFromExcelRequest,
        __Marshaller_catalog_UploadCatalogFromExcelResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.SaveCatalogFromExcelRequest, global::protos.SaveCatalogFromExcelResponse> __Method_SaveCatalogFromExcel = new grpc::Method<global::protos.SaveCatalogFromExcelRequest, global::protos.SaveCatalogFromExcelResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SaveCatalogFromExcel",
        __Marshaller_catalog_SaveCatalogFromExcelRequest,
        __Marshaller_catalog_SaveCatalogFromExcelResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::protos.CatalogReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of CatalogService</summary>
    [grpc::BindServiceMethod(typeof(CatalogService), "BindService")]
    public abstract partial class CatalogServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.CatalogListResponse> GetListCatalog(global::protos.CatalogListRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.CatalogResponse> GetCatalog(global::protos.CatalogRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.CatalogDeleteResponse> DeleteCatalog(global::protos.CatalogRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.SaveCatalogResponse> SaveCatalog(global::protos.SaveCatalogRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.CatalogResponse> GetLastCatalog(global::protos.CatalogListRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.CatalogResponse> GetMaxCatalog(global::protos.CatalogListRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.CatalogTreeListResponse> GetListCatalogTree(global::protos.CatalogTreeListRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.CatalogTreeResponse> GetCatalogTree(global::protos.CatalogTreeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.CatalogTreeDeleteResponse> DeleteCatalogTree(global::protos.CatalogTreeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.SaveCatalogTreeResponse> SaveCatalogTree(global::protos.SaveCatalogTreeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.CatalogTreeResponse> GetLastCatalogTree(global::protos.CatalogTreeListRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.CatalogTreeResponse> GetMaxCatalogTree(global::protos.CatalogTreeListRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.SaveCatalogTreeResponse> ReorderCatalogTree(global::protos.ReorderCatalogTreeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.UploadCatalogFromExcelResponse> UploadCatalogFromExcel(global::protos.UploadCatalogFromExcelRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.SaveCatalogFromExcelResponse> SaveCatalogFromExcel(global::protos.SaveCatalogFromExcelRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(CatalogServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetListCatalog, serviceImpl.GetListCatalog)
          .AddMethod(__Method_GetCatalog, serviceImpl.GetCatalog)
          .AddMethod(__Method_DeleteCatalog, serviceImpl.DeleteCatalog)
          .AddMethod(__Method_SaveCatalog, serviceImpl.SaveCatalog)
          .AddMethod(__Method_GetLastCatalog, serviceImpl.GetLastCatalog)
          .AddMethod(__Method_GetMaxCatalog, serviceImpl.GetMaxCatalog)
          .AddMethod(__Method_GetListCatalogTree, serviceImpl.GetListCatalogTree)
          .AddMethod(__Method_GetCatalogTree, serviceImpl.GetCatalogTree)
          .AddMethod(__Method_DeleteCatalogTree, serviceImpl.DeleteCatalogTree)
          .AddMethod(__Method_SaveCatalogTree, serviceImpl.SaveCatalogTree)
          .AddMethod(__Method_GetLastCatalogTree, serviceImpl.GetLastCatalogTree)
          .AddMethod(__Method_GetMaxCatalogTree, serviceImpl.GetMaxCatalogTree)
          .AddMethod(__Method_ReorderCatalogTree, serviceImpl.ReorderCatalogTree)
          .AddMethod(__Method_UploadCatalogFromExcel, serviceImpl.UploadCatalogFromExcel)
          .AddMethod(__Method_SaveCatalogFromExcel, serviceImpl.SaveCatalogFromExcel).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, CatalogServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetListCatalog, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.CatalogListRequest, global::protos.CatalogListResponse>(serviceImpl.GetListCatalog));
      serviceBinder.AddMethod(__Method_GetCatalog, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.CatalogRequest, global::protos.CatalogResponse>(serviceImpl.GetCatalog));
      serviceBinder.AddMethod(__Method_DeleteCatalog, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.CatalogRequest, global::protos.CatalogDeleteResponse>(serviceImpl.DeleteCatalog));
      serviceBinder.AddMethod(__Method_SaveCatalog, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.SaveCatalogRequest, global::protos.SaveCatalogResponse>(serviceImpl.SaveCatalog));
      serviceBinder.AddMethod(__Method_GetLastCatalog, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.CatalogListRequest, global::protos.CatalogResponse>(serviceImpl.GetLastCatalog));
      serviceBinder.AddMethod(__Method_GetMaxCatalog, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.CatalogListRequest, global::protos.CatalogResponse>(serviceImpl.GetMaxCatalog));
      serviceBinder.AddMethod(__Method_GetListCatalogTree, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.CatalogTreeListRequest, global::protos.CatalogTreeListResponse>(serviceImpl.GetListCatalogTree));
      serviceBinder.AddMethod(__Method_GetCatalogTree, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.CatalogTreeRequest, global::protos.CatalogTreeResponse>(serviceImpl.GetCatalogTree));
      serviceBinder.AddMethod(__Method_DeleteCatalogTree, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.CatalogTreeRequest, global::protos.CatalogTreeDeleteResponse>(serviceImpl.DeleteCatalogTree));
      serviceBinder.AddMethod(__Method_SaveCatalogTree, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.SaveCatalogTreeRequest, global::protos.SaveCatalogTreeResponse>(serviceImpl.SaveCatalogTree));
      serviceBinder.AddMethod(__Method_GetLastCatalogTree, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.CatalogTreeListRequest, global::protos.CatalogTreeResponse>(serviceImpl.GetLastCatalogTree));
      serviceBinder.AddMethod(__Method_GetMaxCatalogTree, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.CatalogTreeListRequest, global::protos.CatalogTreeResponse>(serviceImpl.GetMaxCatalogTree));
      serviceBinder.AddMethod(__Method_ReorderCatalogTree, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.ReorderCatalogTreeRequest, global::protos.SaveCatalogTreeResponse>(serviceImpl.ReorderCatalogTree));
      serviceBinder.AddMethod(__Method_UploadCatalogFromExcel, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.UploadCatalogFromExcelRequest, global::protos.UploadCatalogFromExcelResponse>(serviceImpl.UploadCatalogFromExcel));
      serviceBinder.AddMethod(__Method_SaveCatalogFromExcel, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.SaveCatalogFromExcelRequest, global::protos.SaveCatalogFromExcelResponse>(serviceImpl.SaveCatalogFromExcel));
    }

  }
}
#endregion
