// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: DanhMucChuyenNganh.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace protos {
  public static partial class DanhMucChuyenNganhService
  {
    static readonly string __ServiceName = "DanhMucChuyenNganh.DanhMucChuyenNganhService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.DanhMucChuyenNganhListRequest> __Marshaller_DanhMucChuyenNganh_DanhMucChuyenNganhListRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.DanhMucChuyenNganhListRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.DanhMucChuyenNganhListResponse> __Marshaller_DanhMucChuyenNganh_DanhMucChuyenNganhListResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.DanhMucChuyenNganhListResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.DanhMucChuyenNganhGetRequest> __Marshaller_DanhMucChuyenNganh_DanhMucChuyenNganhGetRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.DanhMucChuyenNganhGetRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.DanhMucChuyenNganhGetResponse> __Marshaller_DanhMucChuyenNganh_DanhMucChuyenNganhGetResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.DanhMucChuyenNganhGetResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.DanhMucChuyenNganhSaveRequest> __Marshaller_DanhMucChuyenNganh_DanhMucChuyenNganhSaveRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.DanhMucChuyenNganhSaveRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.DanhMucChuyenNganhSaveResponse> __Marshaller_DanhMucChuyenNganh_DanhMucChuyenNganhSaveResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.DanhMucChuyenNganhSaveResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.DanhMucChuyenNganhDeleteRequest> __Marshaller_DanhMucChuyenNganh_DanhMucChuyenNganhDeleteRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.DanhMucChuyenNganhDeleteRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.DanhMucChuyenNganhDeleteResponse> __Marshaller_DanhMucChuyenNganh_DanhMucChuyenNganhDeleteResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.DanhMucChuyenNganhDeleteResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.DanhMucChuyenNganhListRequest, global::protos.DanhMucChuyenNganhListResponse> __Method_GetList = new grpc::Method<global::protos.DanhMucChuyenNganhListRequest, global::protos.DanhMucChuyenNganhListResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetList",
        __Marshaller_DanhMucChuyenNganh_DanhMucChuyenNganhListRequest,
        __Marshaller_DanhMucChuyenNganh_DanhMucChuyenNganhListResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.DanhMucChuyenNganhGetRequest, global::protos.DanhMucChuyenNganhGetResponse> __Method_Get = new grpc::Method<global::protos.DanhMucChuyenNganhGetRequest, global::protos.DanhMucChuyenNganhGetResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Get",
        __Marshaller_DanhMucChuyenNganh_DanhMucChuyenNganhGetRequest,
        __Marshaller_DanhMucChuyenNganh_DanhMucChuyenNganhGetResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.DanhMucChuyenNganhSaveRequest, global::protos.DanhMucChuyenNganhSaveResponse> __Method_Save = new grpc::Method<global::protos.DanhMucChuyenNganhSaveRequest, global::protos.DanhMucChuyenNganhSaveResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Save",
        __Marshaller_DanhMucChuyenNganh_DanhMucChuyenNganhSaveRequest,
        __Marshaller_DanhMucChuyenNganh_DanhMucChuyenNganhSaveResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.DanhMucChuyenNganhDeleteRequest, global::protos.DanhMucChuyenNganhDeleteResponse> __Method_Delete = new grpc::Method<global::protos.DanhMucChuyenNganhDeleteRequest, global::protos.DanhMucChuyenNganhDeleteResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Delete",
        __Marshaller_DanhMucChuyenNganh_DanhMucChuyenNganhDeleteRequest,
        __Marshaller_DanhMucChuyenNganh_DanhMucChuyenNganhDeleteResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::protos.DanhMucChuyenNganhReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of DanhMucChuyenNganhService</summary>
    [grpc::BindServiceMethod(typeof(DanhMucChuyenNganhService), "BindService")]
    public abstract partial class DanhMucChuyenNganhServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.DanhMucChuyenNganhListResponse> GetList(global::protos.DanhMucChuyenNganhListRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.DanhMucChuyenNganhGetResponse> Get(global::protos.DanhMucChuyenNganhGetRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.DanhMucChuyenNganhSaveResponse> Save(global::protos.DanhMucChuyenNganhSaveRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.DanhMucChuyenNganhDeleteResponse> Delete(global::protos.DanhMucChuyenNganhDeleteRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(DanhMucChuyenNganhServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetList, serviceImpl.GetList)
          .AddMethod(__Method_Get, serviceImpl.Get)
          .AddMethod(__Method_Save, serviceImpl.Save)
          .AddMethod(__Method_Delete, serviceImpl.Delete).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, DanhMucChuyenNganhServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetList, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.DanhMucChuyenNganhListRequest, global::protos.DanhMucChuyenNganhListResponse>(serviceImpl.GetList));
      serviceBinder.AddMethod(__Method_Get, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.DanhMucChuyenNganhGetRequest, global::protos.DanhMucChuyenNganhGetResponse>(serviceImpl.Get));
      serviceBinder.AddMethod(__Method_Save, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.DanhMucChuyenNganhSaveRequest, global::protos.DanhMucChuyenNganhSaveResponse>(serviceImpl.Save));
      serviceBinder.AddMethod(__Method_Delete, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.DanhMucChuyenNganhDeleteRequest, global::protos.DanhMucChuyenNganhDeleteResponse>(serviceImpl.Delete));
    }

  }
}
#endregion
