// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: DanhMucTrangBi.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace protos {
  public static partial class DanhMucTrangBiService
  {
    static readonly string __ServiceName = "DanhMucTrangBi.DanhMucTrangBiService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.GetListMaDinhDanhTrangBiRequest> __Marshaller_DanhMucTrangBi_GetListMaDinhDanhTrangBiRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.GetListMaDinhDanhTrangBiRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.GetListMaDinhDanhTrangBiResponse> __Marshaller_DanhMucTrangBi_GetListMaDinhDanhTrangBiResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.GetListMaDinhDanhTrangBiResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.TrangBiTreeListRequest> __Marshaller_DanhMucTrangBi_TrangBiTreeListRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.TrangBiTreeListRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.TrangBiTreeListResponse> __Marshaller_DanhMucTrangBi_TrangBiTreeListResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.TrangBiTreeListResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.TrangBiTreeGetRequest> __Marshaller_DanhMucTrangBi_TrangBiTreeGetRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.TrangBiTreeGetRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.TrangBiTreeGetResponse> __Marshaller_DanhMucTrangBi_TrangBiTreeGetResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.TrangBiTreeGetResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.SaveTrangBiTreeRequest> __Marshaller_DanhMucTrangBi_SaveTrangBiTreeRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.SaveTrangBiTreeRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.SaveTrangBiTreeResponse> __Marshaller_DanhMucTrangBi_SaveTrangBiTreeResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.SaveTrangBiTreeResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.DeleteTrangBiTreeRequest> __Marshaller_DanhMucTrangBi_DeleteTrangBiTreeRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.DeleteTrangBiTreeRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.DeleteTrangBiTreeResponse> __Marshaller_DanhMucTrangBi_DeleteTrangBiTreeResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.DeleteTrangBiTreeResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.GetFieldSetsByMaDanhMucRequest> __Marshaller_DanhMucTrangBi_GetFieldSetsByMaDanhMucRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.GetFieldSetsByMaDanhMucRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.GetFieldSetsByMaDanhMucResponse> __Marshaller_DanhMucTrangBi_GetFieldSetsByMaDanhMucResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.GetFieldSetsByMaDanhMucResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.SaveTrangBiNhom1Request> __Marshaller_DanhMucTrangBi_SaveTrangBiNhom1Request = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.SaveTrangBiNhom1Request.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.SaveTrangBiNhom1Response> __Marshaller_DanhMucTrangBi_SaveTrangBiNhom1Response = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.SaveTrangBiNhom1Response.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.GetListTrangBiNhom1Request> __Marshaller_DanhMucTrangBi_GetListTrangBiNhom1Request = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.GetListTrangBiNhom1Request.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.GetListTrangBiNhom1Response> __Marshaller_DanhMucTrangBi_GetListTrangBiNhom1Response = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.GetListTrangBiNhom1Response.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.GetTrangBiNhom1Request> __Marshaller_DanhMucTrangBi_GetTrangBiNhom1Request = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.GetTrangBiNhom1Request.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.GetTrangBiNhom1Response> __Marshaller_DanhMucTrangBi_GetTrangBiNhom1Response = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.GetTrangBiNhom1Response.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.SaveTrangBiNhom2Request> __Marshaller_DanhMucTrangBi_SaveTrangBiNhom2Request = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.SaveTrangBiNhom2Request.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.SaveTrangBiNhom2Response> __Marshaller_DanhMucTrangBi_SaveTrangBiNhom2Response = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.SaveTrangBiNhom2Response.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.GetListTrangBiNhom2Request> __Marshaller_DanhMucTrangBi_GetListTrangBiNhom2Request = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.GetListTrangBiNhom2Request.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.GetListTrangBiNhom2Response> __Marshaller_DanhMucTrangBi_GetListTrangBiNhom2Response = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.GetListTrangBiNhom2Response.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.GetTrangBiNhom2Request> __Marshaller_DanhMucTrangBi_GetTrangBiNhom2Request = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.GetTrangBiNhom2Request.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.GetTrangBiNhom2Response> __Marshaller_DanhMucTrangBi_GetTrangBiNhom2Response = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.GetTrangBiNhom2Response.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.GetListMaDinhDanhTrangBiRequest, global::protos.GetListMaDinhDanhTrangBiResponse> __Method_GetListMaDinhDanhTrangBi = new grpc::Method<global::protos.GetListMaDinhDanhTrangBiRequest, global::protos.GetListMaDinhDanhTrangBiResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetListMaDinhDanhTrangBi",
        __Marshaller_DanhMucTrangBi_GetListMaDinhDanhTrangBiRequest,
        __Marshaller_DanhMucTrangBi_GetListMaDinhDanhTrangBiResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.TrangBiTreeListRequest, global::protos.TrangBiTreeListResponse> __Method_GetListTree = new grpc::Method<global::protos.TrangBiTreeListRequest, global::protos.TrangBiTreeListResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetListTree",
        __Marshaller_DanhMucTrangBi_TrangBiTreeListRequest,
        __Marshaller_DanhMucTrangBi_TrangBiTreeListResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.TrangBiTreeGetRequest, global::protos.TrangBiTreeGetResponse> __Method_GetTree = new grpc::Method<global::protos.TrangBiTreeGetRequest, global::protos.TrangBiTreeGetResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetTree",
        __Marshaller_DanhMucTrangBi_TrangBiTreeGetRequest,
        __Marshaller_DanhMucTrangBi_TrangBiTreeGetResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.SaveTrangBiTreeRequest, global::protos.SaveTrangBiTreeResponse> __Method_SaveTree = new grpc::Method<global::protos.SaveTrangBiTreeRequest, global::protos.SaveTrangBiTreeResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SaveTree",
        __Marshaller_DanhMucTrangBi_SaveTrangBiTreeRequest,
        __Marshaller_DanhMucTrangBi_SaveTrangBiTreeResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.DeleteTrangBiTreeRequest, global::protos.DeleteTrangBiTreeResponse> __Method_DeleteTree = new grpc::Method<global::protos.DeleteTrangBiTreeRequest, global::protos.DeleteTrangBiTreeResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteTree",
        __Marshaller_DanhMucTrangBi_DeleteTrangBiTreeRequest,
        __Marshaller_DanhMucTrangBi_DeleteTrangBiTreeResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.GetFieldSetsByMaDanhMucRequest, global::protos.GetFieldSetsByMaDanhMucResponse> __Method_GetFieldSetsByMaDanhMuc = new grpc::Method<global::protos.GetFieldSetsByMaDanhMucRequest, global::protos.GetFieldSetsByMaDanhMucResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetFieldSetsByMaDanhMuc",
        __Marshaller_DanhMucTrangBi_GetFieldSetsByMaDanhMucRequest,
        __Marshaller_DanhMucTrangBi_GetFieldSetsByMaDanhMucResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.SaveTrangBiNhom1Request, global::protos.SaveTrangBiNhom1Response> __Method_SaveTrangBiNhom1 = new grpc::Method<global::protos.SaveTrangBiNhom1Request, global::protos.SaveTrangBiNhom1Response>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SaveTrangBiNhom1",
        __Marshaller_DanhMucTrangBi_SaveTrangBiNhom1Request,
        __Marshaller_DanhMucTrangBi_SaveTrangBiNhom1Response);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.GetListTrangBiNhom1Request, global::protos.GetListTrangBiNhom1Response> __Method_GetListTrangBiNhom1 = new grpc::Method<global::protos.GetListTrangBiNhom1Request, global::protos.GetListTrangBiNhom1Response>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetListTrangBiNhom1",
        __Marshaller_DanhMucTrangBi_GetListTrangBiNhom1Request,
        __Marshaller_DanhMucTrangBi_GetListTrangBiNhom1Response);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.GetTrangBiNhom1Request, global::protos.GetTrangBiNhom1Response> __Method_GetTrangBiNhom1 = new grpc::Method<global::protos.GetTrangBiNhom1Request, global::protos.GetTrangBiNhom1Response>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetTrangBiNhom1",
        __Marshaller_DanhMucTrangBi_GetTrangBiNhom1Request,
        __Marshaller_DanhMucTrangBi_GetTrangBiNhom1Response);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.SaveTrangBiNhom2Request, global::protos.SaveTrangBiNhom2Response> __Method_SaveTrangBiNhom2 = new grpc::Method<global::protos.SaveTrangBiNhom2Request, global::protos.SaveTrangBiNhom2Response>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SaveTrangBiNhom2",
        __Marshaller_DanhMucTrangBi_SaveTrangBiNhom2Request,
        __Marshaller_DanhMucTrangBi_SaveTrangBiNhom2Response);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.GetListTrangBiNhom2Request, global::protos.GetListTrangBiNhom2Response> __Method_GetListTrangBiNhom2 = new grpc::Method<global::protos.GetListTrangBiNhom2Request, global::protos.GetListTrangBiNhom2Response>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetListTrangBiNhom2",
        __Marshaller_DanhMucTrangBi_GetListTrangBiNhom2Request,
        __Marshaller_DanhMucTrangBi_GetListTrangBiNhom2Response);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.GetTrangBiNhom2Request, global::protos.GetTrangBiNhom2Response> __Method_GetTrangBiNhom2 = new grpc::Method<global::protos.GetTrangBiNhom2Request, global::protos.GetTrangBiNhom2Response>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetTrangBiNhom2",
        __Marshaller_DanhMucTrangBi_GetTrangBiNhom2Request,
        __Marshaller_DanhMucTrangBi_GetTrangBiNhom2Response);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::protos.DanhMucTrangBiReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of DanhMucTrangBiService</summary>
    [grpc::BindServiceMethod(typeof(DanhMucTrangBiService), "BindService")]
    public abstract partial class DanhMucTrangBiServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.GetListMaDinhDanhTrangBiResponse> GetListMaDinhDanhTrangBi(global::protos.GetListMaDinhDanhTrangBiRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.TrangBiTreeListResponse> GetListTree(global::protos.TrangBiTreeListRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.TrangBiTreeGetResponse> GetTree(global::protos.TrangBiTreeGetRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.SaveTrangBiTreeResponse> SaveTree(global::protos.SaveTrangBiTreeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.DeleteTrangBiTreeResponse> DeleteTree(global::protos.DeleteTrangBiTreeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.GetFieldSetsByMaDanhMucResponse> GetFieldSetsByMaDanhMuc(global::protos.GetFieldSetsByMaDanhMucRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.SaveTrangBiNhom1Response> SaveTrangBiNhom1(global::protos.SaveTrangBiNhom1Request request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.GetListTrangBiNhom1Response> GetListTrangBiNhom1(global::protos.GetListTrangBiNhom1Request request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.GetTrangBiNhom1Response> GetTrangBiNhom1(global::protos.GetTrangBiNhom1Request request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.SaveTrangBiNhom2Response> SaveTrangBiNhom2(global::protos.SaveTrangBiNhom2Request request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.GetListTrangBiNhom2Response> GetListTrangBiNhom2(global::protos.GetListTrangBiNhom2Request request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.GetTrangBiNhom2Response> GetTrangBiNhom2(global::protos.GetTrangBiNhom2Request request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(DanhMucTrangBiServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetListMaDinhDanhTrangBi, serviceImpl.GetListMaDinhDanhTrangBi)
          .AddMethod(__Method_GetListTree, serviceImpl.GetListTree)
          .AddMethod(__Method_GetTree, serviceImpl.GetTree)
          .AddMethod(__Method_SaveTree, serviceImpl.SaveTree)
          .AddMethod(__Method_DeleteTree, serviceImpl.DeleteTree)
          .AddMethod(__Method_GetFieldSetsByMaDanhMuc, serviceImpl.GetFieldSetsByMaDanhMuc)
          .AddMethod(__Method_SaveTrangBiNhom1, serviceImpl.SaveTrangBiNhom1)
          .AddMethod(__Method_GetListTrangBiNhom1, serviceImpl.GetListTrangBiNhom1)
          .AddMethod(__Method_GetTrangBiNhom1, serviceImpl.GetTrangBiNhom1)
          .AddMethod(__Method_SaveTrangBiNhom2, serviceImpl.SaveTrangBiNhom2)
          .AddMethod(__Method_GetListTrangBiNhom2, serviceImpl.GetListTrangBiNhom2)
          .AddMethod(__Method_GetTrangBiNhom2, serviceImpl.GetTrangBiNhom2).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, DanhMucTrangBiServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetListMaDinhDanhTrangBi, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.GetListMaDinhDanhTrangBiRequest, global::protos.GetListMaDinhDanhTrangBiResponse>(serviceImpl.GetListMaDinhDanhTrangBi));
      serviceBinder.AddMethod(__Method_GetListTree, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.TrangBiTreeListRequest, global::protos.TrangBiTreeListResponse>(serviceImpl.GetListTree));
      serviceBinder.AddMethod(__Method_GetTree, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.TrangBiTreeGetRequest, global::protos.TrangBiTreeGetResponse>(serviceImpl.GetTree));
      serviceBinder.AddMethod(__Method_SaveTree, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.SaveTrangBiTreeRequest, global::protos.SaveTrangBiTreeResponse>(serviceImpl.SaveTree));
      serviceBinder.AddMethod(__Method_DeleteTree, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.DeleteTrangBiTreeRequest, global::protos.DeleteTrangBiTreeResponse>(serviceImpl.DeleteTree));
      serviceBinder.AddMethod(__Method_GetFieldSetsByMaDanhMuc, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.GetFieldSetsByMaDanhMucRequest, global::protos.GetFieldSetsByMaDanhMucResponse>(serviceImpl.GetFieldSetsByMaDanhMuc));
      serviceBinder.AddMethod(__Method_SaveTrangBiNhom1, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.SaveTrangBiNhom1Request, global::protos.SaveTrangBiNhom1Response>(serviceImpl.SaveTrangBiNhom1));
      serviceBinder.AddMethod(__Method_GetListTrangBiNhom1, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.GetListTrangBiNhom1Request, global::protos.GetListTrangBiNhom1Response>(serviceImpl.GetListTrangBiNhom1));
      serviceBinder.AddMethod(__Method_GetTrangBiNhom1, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.GetTrangBiNhom1Request, global::protos.GetTrangBiNhom1Response>(serviceImpl.GetTrangBiNhom1));
      serviceBinder.AddMethod(__Method_SaveTrangBiNhom2, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.SaveTrangBiNhom2Request, global::protos.SaveTrangBiNhom2Response>(serviceImpl.SaveTrangBiNhom2));
      serviceBinder.AddMethod(__Method_GetListTrangBiNhom2, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.GetListTrangBiNhom2Request, global::protos.GetListTrangBiNhom2Response>(serviceImpl.GetListTrangBiNhom2));
      serviceBinder.AddMethod(__Method_GetTrangBiNhom2, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.GetTrangBiNhom2Request, global::protos.GetTrangBiNhom2Response>(serviceImpl.GetTrangBiNhom2));
    }

  }
}
#endregion
