// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Employee.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace protos {
  public static partial class EmployeeService
  {
    static readonly string __ServiceName = "Employee.EmployeeService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.GetListEmployeesRequest> __Marshaller_Employee_GetListEmployeesRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.GetListEmployeesRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.GetListEmployeesResponse> __Marshaller_Employee_GetListEmployeesResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.GetListEmployeesResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.GetEmployeeRequest> __Marshaller_Employee_GetEmployeeRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.GetEmployeeRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.GetEmployeeResponse> __Marshaller_Employee_GetEmployeeResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.GetEmployeeResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.SaveEmployeeRequest> __Marshaller_Employee_SaveEmployeeRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.SaveEmployeeRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.SaveEmployeeResponse> __Marshaller_Employee_SaveEmployeeResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.SaveEmployeeResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.ImportEmployeesStreamRequest> __Marshaller_Employee_ImportEmployeesStreamRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.ImportEmployeesStreamRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.ImportEmployeesStreamEvent> __Marshaller_Employee_ImportEmployeesStreamEvent = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.ImportEmployeesStreamEvent.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.DeleteEmployeeRequest> __Marshaller_Employee_DeleteEmployeeRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.DeleteEmployeeRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.DeleteEmployeeResponse> __Marshaller_Employee_DeleteEmployeeResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.DeleteEmployeeResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.GetListEmployeesRequest, global::protos.GetListEmployeesResponse> __Method_GetListEmployees = new grpc::Method<global::protos.GetListEmployeesRequest, global::protos.GetListEmployeesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetListEmployees",
        __Marshaller_Employee_GetListEmployeesRequest,
        __Marshaller_Employee_GetListEmployeesResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.GetEmployeeRequest, global::protos.GetEmployeeResponse> __Method_GetEmployee = new grpc::Method<global::protos.GetEmployeeRequest, global::protos.GetEmployeeResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetEmployee",
        __Marshaller_Employee_GetEmployeeRequest,
        __Marshaller_Employee_GetEmployeeResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.SaveEmployeeRequest, global::protos.SaveEmployeeResponse> __Method_SaveEmployee = new grpc::Method<global::protos.SaveEmployeeRequest, global::protos.SaveEmployeeResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SaveEmployee",
        __Marshaller_Employee_SaveEmployeeRequest,
        __Marshaller_Employee_SaveEmployeeResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.ImportEmployeesStreamRequest, global::protos.ImportEmployeesStreamEvent> __Method_ImportEmployeesStream = new grpc::Method<global::protos.ImportEmployeesStreamRequest, global::protos.ImportEmployeesStreamEvent>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "ImportEmployeesStream",
        __Marshaller_Employee_ImportEmployeesStreamRequest,
        __Marshaller_Employee_ImportEmployeesStreamEvent);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.DeleteEmployeeRequest, global::protos.DeleteEmployeeResponse> __Method_DeleteEmployee = new grpc::Method<global::protos.DeleteEmployeeRequest, global::protos.DeleteEmployeeResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteEmployee",
        __Marshaller_Employee_DeleteEmployeeRequest,
        __Marshaller_Employee_DeleteEmployeeResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::protos.EmployeeReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of EmployeeService</summary>
    [grpc::BindServiceMethod(typeof(EmployeeService), "BindService")]
    public abstract partial class EmployeeServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.GetListEmployeesResponse> GetListEmployees(global::protos.GetListEmployeesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.GetEmployeeResponse> GetEmployee(global::protos.GetEmployeeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.SaveEmployeeResponse> SaveEmployee(global::protos.SaveEmployeeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task ImportEmployeesStream(global::protos.ImportEmployeesStreamRequest request, grpc::IServerStreamWriter<global::protos.ImportEmployeesStreamEvent> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.DeleteEmployeeResponse> DeleteEmployee(global::protos.DeleteEmployeeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(EmployeeServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetListEmployees, serviceImpl.GetListEmployees)
          .AddMethod(__Method_GetEmployee, serviceImpl.GetEmployee)
          .AddMethod(__Method_SaveEmployee, serviceImpl.SaveEmployee)
          .AddMethod(__Method_ImportEmployeesStream, serviceImpl.ImportEmployeesStream)
          .AddMethod(__Method_DeleteEmployee, serviceImpl.DeleteEmployee).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, EmployeeServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetListEmployees, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.GetListEmployeesRequest, global::protos.GetListEmployeesResponse>(serviceImpl.GetListEmployees));
      serviceBinder.AddMethod(__Method_GetEmployee, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.GetEmployeeRequest, global::protos.GetEmployeeResponse>(serviceImpl.GetEmployee));
      serviceBinder.AddMethod(__Method_SaveEmployee, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.SaveEmployeeRequest, global::protos.SaveEmployeeResponse>(serviceImpl.SaveEmployee));
      serviceBinder.AddMethod(__Method_ImportEmployeesStream, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::protos.ImportEmployeesStreamRequest, global::protos.ImportEmployeesStreamEvent>(serviceImpl.ImportEmployeesStream));
      serviceBinder.AddMethod(__Method_DeleteEmployee, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.DeleteEmployeeRequest, global::protos.DeleteEmployeeResponse>(serviceImpl.DeleteEmployee));
    }

  }
}
#endregion
