// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace protos {

  /// <summary>Holder for reflection information generated from Enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpFbnVtLnByb3RvEgRFbnVtKiMKBlN0YXR1cxIICgROT05FEAASBwoDT0ZG",
            "EAESBgoCT04QAiqYAgoORmlsdGVyT3BlcmF0b3ISCgoGRVFVQUxTEAASDgoK",
            "Tk9UX0VRVUFMUxABEg0KCUxFU1NfVEhBThACEhcKE0xFU1NfVEhBTl9PUl9F",
            "UVVBTFMQAxIQCgxHUkVBVEVSX1RIQU4QBBIaChZHUkVBVEVSX1RIQU5fT1Jf",
            "RVFVQUxTEAUSDAoIQ09OVEFJTlMQBhIPCgtTVEFSVFNfV0lUSBAHEg0KCUVO",
            "RFNfV0lUSBAIEhQKEERPRVNfTk9UX0NPTlRBSU4QCRIGCgJJThAKEgoKBk5P",
            "VF9JThALEgsKB0lTX05VTEwQDBIMCghJU19FTVBUWRANEg8KC0lTX05PVF9O",
            "VUxMEA4SEAoMSVNfTk9UX0VNUFRZEA8qKAoVTG9naWNhbEZpbHRlck9wZXJh",
            "dG9yEgcKA0FORBAAEgYKAk9SEAEqKwoLT3JpZW50YXRpb24SDAoIVkVSVElD",
            "QUwQABIOCgpIT1JJWk9OVEFMEAEqNwoHVmFyaWFudBIKCgZGSUxMRUQQABII",
            "CgRGTEFUEAESCAoEVEVYVBACEgwKCE9VVExJTkVEEANCCaoCBnByb3Rvc2IG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::protos.Status), typeof(global::protos.FilterOperator), typeof(global::protos.LogicalFilterOperator), typeof(global::protos.Orientation), typeof(global::protos.Variant), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum Status {
    [pbr::OriginalName("NONE")] None = 0,
    [pbr::OriginalName("OFF")] Off = 1,
    [pbr::OriginalName("ON")] On = 2,
  }

  public enum FilterOperator {
    [pbr::OriginalName("EQUALS")] Equals = 0,
    [pbr::OriginalName("NOT_EQUALS")] NotEquals = 1,
    [pbr::OriginalName("LESS_THAN")] LessThan = 2,
    [pbr::OriginalName("LESS_THAN_OR_EQUALS")] LessThanOrEquals = 3,
    [pbr::OriginalName("GREATER_THAN")] GreaterThan = 4,
    [pbr::OriginalName("GREATER_THAN_OR_EQUALS")] GreaterThanOrEquals = 5,
    [pbr::OriginalName("CONTAINS")] Contains = 6,
    [pbr::OriginalName("STARTS_WITH")] StartsWith = 7,
    [pbr::OriginalName("ENDS_WITH")] EndsWith = 8,
    [pbr::OriginalName("DOES_NOT_CONTAIN")] DoesNotContain = 9,
    [pbr::OriginalName("IN")] In = 10,
    [pbr::OriginalName("NOT_IN")] NotIn = 11,
    [pbr::OriginalName("IS_NULL")] IsNull = 12,
    [pbr::OriginalName("IS_EMPTY")] IsEmpty = 13,
    [pbr::OriginalName("IS_NOT_NULL")] IsNotNull = 14,
    [pbr::OriginalName("IS_NOT_EMPTY")] IsNotEmpty = 15,
  }

  public enum LogicalFilterOperator {
    [pbr::OriginalName("AND")] And = 0,
    [pbr::OriginalName("OR")] Or = 1,
  }

  public enum Orientation {
    [pbr::OriginalName("VERTICAL")] Vertical = 0,
    [pbr::OriginalName("HORIZONTAL")] Horizontal = 1,
  }

  public enum Variant {
    [pbr::OriginalName("FILLED")] Filled = 0,
    [pbr::OriginalName("FLAT")] Flat = 1,
    [pbr::OriginalName("TEXT")] Text = 2,
    [pbr::OriginalName("OUTLINED")] Outlined = 3,
  }

  #endregion

}

#endregion Designer generated code
