// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ExtendedField.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace protos {

  /// <summary>Holder for reflection information generated from ExtendedField.proto</summary>
  public static partial class ExtendedFieldReflection {

    #region Descriptor
    /// <summary>File descriptor for ExtendedField.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ExtendedFieldReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNFeHRlbmRlZEZpZWxkLnByb3RvEg1FeHRlbmRlZEZpZWxkGh5nb29nbGUv",
            "cHJvdG9idWYvd3JhcHBlcnMucHJvdG8aH2dvb2dsZS9wcm90b2J1Zi90aW1l",
            "c3RhbXAucHJvdG8aCkJhc2UucHJvdG8i/gIKDUV4dGVuZGVkRmllbGQSCgoC",
            "aWQYASABKAkSEAoIb3duZXJfaWQYAiABKAkSEgoKb3duZXJfbmFtZRgDIAEo",
            "CRIMCgRuYW1lGAQgASgJEi4KCWludF92YWx1ZRgFIAEoCzIbLmdvb2dsZS5w",
            "cm90b2J1Zi5JbnQzMlZhbHVlEi4KCmJvb2xfdmFsdWUYBiABKAsyGi5nb29n",
            "bGUucHJvdG9idWYuQm9vbFZhbHVlEjIKDHN0cmluZ192YWx1ZRgHIAEoCzIc",
            "Lmdvb2dsZS5wcm90b2J1Zi5TdHJpbmdWYWx1ZRIyCgxkb3VibGVfdmFsdWUY",
            "CCABKAsyHC5nb29nbGUucHJvdG9idWYuRG91YmxlVmFsdWUSMwoPZGF0ZV90",
            "aW1lX3ZhbHVlGAkgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIw",
            "CgtieXRlc192YWx1ZRgKIAEoCzIbLmdvb2dsZS5wcm90b2J1Zi5CeXRlc1Zh",
            "bHVlIuMDChRFeHRlbmRQcm9wZXJ0eURlZmluZRIMCgRuYW1lGAEgASgJEg8K",
            "B2NhcHRpb24YAiABKAkSMgoMY2F0YWxvZ19uYW1lGAMgASgLMhwuZ29vZ2xl",
            "LnByb3RvYnVmLlN0cmluZ1ZhbHVlEioKCWRhdGFfdHlwZRgEIAEoDjIXLkV4",
            "dGVuZGVkRmllbGQuRGF0YVR5cGUSRQofY2F0YWxvZ19uYW1lX2Zvcl9kYXRh",
            "X3R5cGVfbGlzdBgFIAEoCzIcLmdvb2dsZS5wcm90b2J1Zi5TdHJpbmdWYWx1",
            "ZRILCgNtaW4YBiABKAESCwoDbWF4GAcgASgBEhAKCG11bHRpcGxlGAggASgI",
            "EicKB2ZpbHRlcnMYCSADKAsyFi5CYXNlLkZpbHRlckRlc2NyaXB0b3ISFgoO",
            "aW5jbHVkZV9maWVsZHMYCiADKAkSJgoHb3B0aW9ucxgLIAMoCzIVLkV4dGVu",
            "ZGVkRmllbGQuT3B0aW9uEhMKC2lzX3JlcXVpcmVkGAwgASgIEiwKBnN1ZmZp",
            "eBgNIAEoCzIcLmdvb2dsZS5wcm90b2J1Zi5TdHJpbmdWYWx1ZRItCghvcmRl",
            "cmluZxgOIAEoCzIbLmdvb2dsZS5wcm90b2J1Zi5JbnQzMlZhbHVlIiQKBk9w",
            "dGlvbhILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAkqswEKCERhdGFUeXBl",
            "EgcKA0lOVBAAEgoKBkRPVUJMRRABEgoKBlNUUklORxACEg0KCURBVEVfVElN",
            "RRADEggKBFRJTUUQBBIICgRCT09MEAUSCAoETElTVBAGEggKBFRSRUUQBxIJ",
            "CgVDT0xPUhAIEg8KC0ZJTEVfQVRUQUNIEAkSCAoESFRNTBAKEggKBE1FTU8Q",
            "CxIJCgVJTUFHRRAMEgkKBVZJREVPEA0SCQoFTUVESUEQDkIJqgIGcHJvdG9z",
            "YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::protos.BaseReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::protos.DataType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::protos.ExtendedField), global::protos.ExtendedField.Parser, new[]{ "Id", "OwnerId", "OwnerName", "Name", "IntValue", "BoolValue", "StringValue", "DoubleValue", "DateTimeValue", "BytesValue" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::protos.ExtendPropertyDefine), global::protos.ExtendPropertyDefine.Parser, new[]{ "Name", "Caption", "CatalogName", "DataType", "CatalogNameForDataTypeList", "Min", "Max", "Multiple", "Filters", "IncludeFields", "Options", "IsRequired", "Suffix", "Ordering" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::protos.Option), global::protos.Option.Parser, new[]{ "Key", "Value" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum DataType {
    [pbr::OriginalName("INT")] Int = 0,
    [pbr::OriginalName("DOUBLE")] Double = 1,
    [pbr::OriginalName("STRING")] String = 2,
    [pbr::OriginalName("DATE_TIME")] DateTime = 3,
    [pbr::OriginalName("TIME")] Time = 4,
    [pbr::OriginalName("BOOL")] Bool = 5,
    [pbr::OriginalName("LIST")] List = 6,
    [pbr::OriginalName("TREE")] Tree = 7,
    [pbr::OriginalName("COLOR")] Color = 8,
    [pbr::OriginalName("FILE_ATTACH")] FileAttach = 9,
    [pbr::OriginalName("HTML")] Html = 10,
    [pbr::OriginalName("MEMO")] Memo = 11,
    [pbr::OriginalName("IMAGE")] Image = 12,
    [pbr::OriginalName("VIDEO")] Video = 13,
    [pbr::OriginalName("MEDIA")] Media = 14,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ExtendedField : pb::IMessage<ExtendedField>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ExtendedField> _parser = new pb::MessageParser<ExtendedField>(() => new ExtendedField());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ExtendedField> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::protos.ExtendedFieldReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExtendedField() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExtendedField(ExtendedField other) : this() {
      id_ = other.id_;
      ownerId_ = other.ownerId_;
      ownerName_ = other.ownerName_;
      name_ = other.name_;
      IntValue = other.IntValue;
      BoolValue = other.BoolValue;
      StringValue = other.StringValue;
      DoubleValue = other.DoubleValue;
      dateTimeValue_ = other.dateTimeValue_ != null ? other.dateTimeValue_.Clone() : null;
      BytesValue = other.BytesValue;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExtendedField Clone() {
      return new ExtendedField(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "owner_id" field.</summary>
    public const int OwnerIdFieldNumber = 2;
    private string ownerId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OwnerId {
      get { return ownerId_; }
      set {
        ownerId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "owner_name" field.</summary>
    public const int OwnerNameFieldNumber = 3;
    private string ownerName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OwnerName {
      get { return ownerName_; }
      set {
        ownerName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 4;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "int_value" field.</summary>
    public const int IntValueFieldNumber = 5;
    private static readonly pb::FieldCodec<int?> _single_intValue_codec = pb::FieldCodec.ForStructWrapper<int>(42);
    private int? intValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int? IntValue {
      get { return intValue_; }
      set {
        intValue_ = value;
      }
    }


    /// <summary>Field number for the "bool_value" field.</summary>
    public const int BoolValueFieldNumber = 6;
    private static readonly pb::FieldCodec<bool?> _single_boolValue_codec = pb::FieldCodec.ForStructWrapper<bool>(50);
    private bool? boolValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool? BoolValue {
      get { return boolValue_; }
      set {
        boolValue_ = value;
      }
    }


    /// <summary>Field number for the "string_value" field.</summary>
    public const int StringValueFieldNumber = 7;
    private static readonly pb::FieldCodec<string> _single_stringValue_codec = pb::FieldCodec.ForClassWrapper<string>(58);
    private string stringValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string StringValue {
      get { return stringValue_; }
      set {
        stringValue_ = value;
      }
    }


    /// <summary>Field number for the "double_value" field.</summary>
    public const int DoubleValueFieldNumber = 8;
    private static readonly pb::FieldCodec<double?> _single_doubleValue_codec = pb::FieldCodec.ForStructWrapper<double>(66);
    private double? doubleValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double? DoubleValue {
      get { return doubleValue_; }
      set {
        doubleValue_ = value;
      }
    }


    /// <summary>Field number for the "date_time_value" field.</summary>
    public const int DateTimeValueFieldNumber = 9;
    private global::Google.Protobuf.WellKnownTypes.Timestamp dateTimeValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp DateTimeValue {
      get { return dateTimeValue_; }
      set {
        dateTimeValue_ = value;
      }
    }

    /// <summary>Field number for the "bytes_value" field.</summary>
    public const int BytesValueFieldNumber = 10;
    private static readonly pb::FieldCodec<pb::ByteString> _single_bytesValue_codec = pb::FieldCodec.ForClassWrapper<pb::ByteString>(82);
    private pb::ByteString bytesValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString BytesValue {
      get { return bytesValue_; }
      set {
        bytesValue_ = value;
      }
    }


    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ExtendedField);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ExtendedField other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (OwnerId != other.OwnerId) return false;
      if (OwnerName != other.OwnerName) return false;
      if (Name != other.Name) return false;
      if (IntValue != other.IntValue) return false;
      if (BoolValue != other.BoolValue) return false;
      if (StringValue != other.StringValue) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseNullableDoubleEqualityComparer.Equals(DoubleValue, other.DoubleValue)) return false;
      if (!object.Equals(DateTimeValue, other.DateTimeValue)) return false;
      if (BytesValue != other.BytesValue) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (OwnerId.Length != 0) hash ^= OwnerId.GetHashCode();
      if (OwnerName.Length != 0) hash ^= OwnerName.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (intValue_ != null) hash ^= IntValue.GetHashCode();
      if (boolValue_ != null) hash ^= BoolValue.GetHashCode();
      if (stringValue_ != null) hash ^= StringValue.GetHashCode();
      if (doubleValue_ != null) hash ^= pbc::ProtobufEqualityComparers.BitwiseNullableDoubleEqualityComparer.GetHashCode(DoubleValue);
      if (dateTimeValue_ != null) hash ^= DateTimeValue.GetHashCode();
      if (bytesValue_ != null) hash ^= BytesValue.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (OwnerId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(OwnerId);
      }
      if (OwnerName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(OwnerName);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Name);
      }
      if (intValue_ != null) {
        _single_intValue_codec.WriteTagAndValue(output, IntValue);
      }
      if (boolValue_ != null) {
        _single_boolValue_codec.WriteTagAndValue(output, BoolValue);
      }
      if (stringValue_ != null) {
        _single_stringValue_codec.WriteTagAndValue(output, StringValue);
      }
      if (doubleValue_ != null) {
        _single_doubleValue_codec.WriteTagAndValue(output, DoubleValue);
      }
      if (dateTimeValue_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(DateTimeValue);
      }
      if (bytesValue_ != null) {
        _single_bytesValue_codec.WriteTagAndValue(output, BytesValue);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (OwnerId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(OwnerId);
      }
      if (OwnerName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(OwnerName);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Name);
      }
      if (intValue_ != null) {
        _single_intValue_codec.WriteTagAndValue(ref output, IntValue);
      }
      if (boolValue_ != null) {
        _single_boolValue_codec.WriteTagAndValue(ref output, BoolValue);
      }
      if (stringValue_ != null) {
        _single_stringValue_codec.WriteTagAndValue(ref output, StringValue);
      }
      if (doubleValue_ != null) {
        _single_doubleValue_codec.WriteTagAndValue(ref output, DoubleValue);
      }
      if (dateTimeValue_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(DateTimeValue);
      }
      if (bytesValue_ != null) {
        _single_bytesValue_codec.WriteTagAndValue(ref output, BytesValue);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (OwnerId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OwnerId);
      }
      if (OwnerName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OwnerName);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (intValue_ != null) {
        size += _single_intValue_codec.CalculateSizeWithTag(IntValue);
      }
      if (boolValue_ != null) {
        size += _single_boolValue_codec.CalculateSizeWithTag(BoolValue);
      }
      if (stringValue_ != null) {
        size += _single_stringValue_codec.CalculateSizeWithTag(StringValue);
      }
      if (doubleValue_ != null) {
        size += _single_doubleValue_codec.CalculateSizeWithTag(DoubleValue);
      }
      if (dateTimeValue_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DateTimeValue);
      }
      if (bytesValue_ != null) {
        size += _single_bytesValue_codec.CalculateSizeWithTag(BytesValue);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ExtendedField other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.OwnerId.Length != 0) {
        OwnerId = other.OwnerId;
      }
      if (other.OwnerName.Length != 0) {
        OwnerName = other.OwnerName;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.intValue_ != null) {
        if (intValue_ == null || other.IntValue != 0) {
          IntValue = other.IntValue;
        }
      }
      if (other.boolValue_ != null) {
        if (boolValue_ == null || other.BoolValue != false) {
          BoolValue = other.BoolValue;
        }
      }
      if (other.stringValue_ != null) {
        if (stringValue_ == null || other.StringValue != "") {
          StringValue = other.StringValue;
        }
      }
      if (other.doubleValue_ != null) {
        if (doubleValue_ == null || other.DoubleValue != 0D) {
          DoubleValue = other.DoubleValue;
        }
      }
      if (other.dateTimeValue_ != null) {
        if (dateTimeValue_ == null) {
          DateTimeValue = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        DateTimeValue.MergeFrom(other.DateTimeValue);
      }
      if (other.bytesValue_ != null) {
        if (bytesValue_ == null || other.BytesValue != pb::ByteString.Empty) {
          BytesValue = other.BytesValue;
        }
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            OwnerId = input.ReadString();
            break;
          }
          case 26: {
            OwnerName = input.ReadString();
            break;
          }
          case 34: {
            Name = input.ReadString();
            break;
          }
          case 42: {
            int? value = _single_intValue_codec.Read(input);
            if (intValue_ == null || value != 0) {
              IntValue = value;
            }
            break;
          }
          case 50: {
            bool? value = _single_boolValue_codec.Read(input);
            if (boolValue_ == null || value != false) {
              BoolValue = value;
            }
            break;
          }
          case 58: {
            string value = _single_stringValue_codec.Read(input);
            if (stringValue_ == null || value != "") {
              StringValue = value;
            }
            break;
          }
          case 66: {
            double? value = _single_doubleValue_codec.Read(input);
            if (doubleValue_ == null || value != 0D) {
              DoubleValue = value;
            }
            break;
          }
          case 74: {
            if (dateTimeValue_ == null) {
              DateTimeValue = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(DateTimeValue);
            break;
          }
          case 82: {
            pb::ByteString value = _single_bytesValue_codec.Read(input);
            if (bytesValue_ == null || value != pb::ByteString.Empty) {
              BytesValue = value;
            }
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            OwnerId = input.ReadString();
            break;
          }
          case 26: {
            OwnerName = input.ReadString();
            break;
          }
          case 34: {
            Name = input.ReadString();
            break;
          }
          case 42: {
            int? value = _single_intValue_codec.Read(ref input);
            if (intValue_ == null || value != 0) {
              IntValue = value;
            }
            break;
          }
          case 50: {
            bool? value = _single_boolValue_codec.Read(ref input);
            if (boolValue_ == null || value != false) {
              BoolValue = value;
            }
            break;
          }
          case 58: {
            string value = _single_stringValue_codec.Read(ref input);
            if (stringValue_ == null || value != "") {
              StringValue = value;
            }
            break;
          }
          case 66: {
            double? value = _single_doubleValue_codec.Read(ref input);
            if (doubleValue_ == null || value != 0D) {
              DoubleValue = value;
            }
            break;
          }
          case 74: {
            if (dateTimeValue_ == null) {
              DateTimeValue = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(DateTimeValue);
            break;
          }
          case 82: {
            pb::ByteString value = _single_bytesValue_codec.Read(ref input);
            if (bytesValue_ == null || value != pb::ByteString.Empty) {
              BytesValue = value;
            }
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ExtendPropertyDefine : pb::IMessage<ExtendPropertyDefine>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ExtendPropertyDefine> _parser = new pb::MessageParser<ExtendPropertyDefine>(() => new ExtendPropertyDefine());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ExtendPropertyDefine> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::protos.ExtendedFieldReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExtendPropertyDefine() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExtendPropertyDefine(ExtendPropertyDefine other) : this() {
      name_ = other.name_;
      caption_ = other.caption_;
      CatalogName = other.CatalogName;
      dataType_ = other.dataType_;
      CatalogNameForDataTypeList = other.CatalogNameForDataTypeList;
      min_ = other.min_;
      max_ = other.max_;
      multiple_ = other.multiple_;
      filters_ = other.filters_.Clone();
      includeFields_ = other.includeFields_.Clone();
      options_ = other.options_.Clone();
      isRequired_ = other.isRequired_;
      Suffix = other.Suffix;
      Ordering = other.Ordering;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExtendPropertyDefine Clone() {
      return new ExtendPropertyDefine(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "caption" field.</summary>
    public const int CaptionFieldNumber = 2;
    private string caption_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Caption {
      get { return caption_; }
      set {
        caption_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "catalog_name" field.</summary>
    public const int CatalogNameFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _single_catalogName_codec = pb::FieldCodec.ForClassWrapper<string>(26);
    private string catalogName_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CatalogName {
      get { return catalogName_; }
      set {
        catalogName_ = value;
      }
    }


    /// <summary>Field number for the "data_type" field.</summary>
    public const int DataTypeFieldNumber = 4;
    private global::protos.DataType dataType_ = global::protos.DataType.Int;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::protos.DataType DataType {
      get { return dataType_; }
      set {
        dataType_ = value;
      }
    }

    /// <summary>Field number for the "catalog_name_for_data_type_list" field.</summary>
    public const int CatalogNameForDataTypeListFieldNumber = 5;
    private static readonly pb::FieldCodec<string> _single_catalogNameForDataTypeList_codec = pb::FieldCodec.ForClassWrapper<string>(42);
    private string catalogNameForDataTypeList_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CatalogNameForDataTypeList {
      get { return catalogNameForDataTypeList_; }
      set {
        catalogNameForDataTypeList_ = value;
      }
    }


    /// <summary>Field number for the "min" field.</summary>
    public const int MinFieldNumber = 6;
    private double min_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Min {
      get { return min_; }
      set {
        min_ = value;
      }
    }

    /// <summary>Field number for the "max" field.</summary>
    public const int MaxFieldNumber = 7;
    private double max_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Max {
      get { return max_; }
      set {
        max_ = value;
      }
    }

    /// <summary>Field number for the "multiple" field.</summary>
    public const int MultipleFieldNumber = 8;
    private bool multiple_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Multiple {
      get { return multiple_; }
      set {
        multiple_ = value;
      }
    }

    /// <summary>Field number for the "filters" field.</summary>
    public const int FiltersFieldNumber = 9;
    private static readonly pb::FieldCodec<global::protos.FilterDescriptor> _repeated_filters_codec
        = pb::FieldCodec.ForMessage(74, global::protos.FilterDescriptor.Parser);
    private readonly pbc::RepeatedField<global::protos.FilterDescriptor> filters_ = new pbc::RepeatedField<global::protos.FilterDescriptor>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::protos.FilterDescriptor> Filters {
      get { return filters_; }
    }

    /// <summary>Field number for the "include_fields" field.</summary>
    public const int IncludeFieldsFieldNumber = 10;
    private static readonly pb::FieldCodec<string> _repeated_includeFields_codec
        = pb::FieldCodec.ForString(82);
    private readonly pbc::RepeatedField<string> includeFields_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> IncludeFields {
      get { return includeFields_; }
    }

    /// <summary>Field number for the "options" field.</summary>
    public const int OptionsFieldNumber = 11;
    private static readonly pb::FieldCodec<global::protos.Option> _repeated_options_codec
        = pb::FieldCodec.ForMessage(90, global::protos.Option.Parser);
    private readonly pbc::RepeatedField<global::protos.Option> options_ = new pbc::RepeatedField<global::protos.Option>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::protos.Option> Options {
      get { return options_; }
    }

    /// <summary>Field number for the "is_required" field.</summary>
    public const int IsRequiredFieldNumber = 12;
    private bool isRequired_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsRequired {
      get { return isRequired_; }
      set {
        isRequired_ = value;
      }
    }

    /// <summary>Field number for the "suffix" field.</summary>
    public const int SuffixFieldNumber = 13;
    private static readonly pb::FieldCodec<string> _single_suffix_codec = pb::FieldCodec.ForClassWrapper<string>(106);
    private string suffix_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Suffix {
      get { return suffix_; }
      set {
        suffix_ = value;
      }
    }


    /// <summary>Field number for the "ordering" field.</summary>
    public const int OrderingFieldNumber = 14;
    private static readonly pb::FieldCodec<int?> _single_ordering_codec = pb::FieldCodec.ForStructWrapper<int>(114);
    private int? ordering_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int? Ordering {
      get { return ordering_; }
      set {
        ordering_ = value;
      }
    }


    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ExtendPropertyDefine);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ExtendPropertyDefine other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Caption != other.Caption) return false;
      if (CatalogName != other.CatalogName) return false;
      if (DataType != other.DataType) return false;
      if (CatalogNameForDataTypeList != other.CatalogNameForDataTypeList) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Min, other.Min)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Max, other.Max)) return false;
      if (Multiple != other.Multiple) return false;
      if(!filters_.Equals(other.filters_)) return false;
      if(!includeFields_.Equals(other.includeFields_)) return false;
      if(!options_.Equals(other.options_)) return false;
      if (IsRequired != other.IsRequired) return false;
      if (Suffix != other.Suffix) return false;
      if (Ordering != other.Ordering) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Caption.Length != 0) hash ^= Caption.GetHashCode();
      if (catalogName_ != null) hash ^= CatalogName.GetHashCode();
      if (DataType != global::protos.DataType.Int) hash ^= DataType.GetHashCode();
      if (catalogNameForDataTypeList_ != null) hash ^= CatalogNameForDataTypeList.GetHashCode();
      if (Min != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Min);
      if (Max != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Max);
      if (Multiple != false) hash ^= Multiple.GetHashCode();
      hash ^= filters_.GetHashCode();
      hash ^= includeFields_.GetHashCode();
      hash ^= options_.GetHashCode();
      if (IsRequired != false) hash ^= IsRequired.GetHashCode();
      if (suffix_ != null) hash ^= Suffix.GetHashCode();
      if (ordering_ != null) hash ^= Ordering.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Caption.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Caption);
      }
      if (catalogName_ != null) {
        _single_catalogName_codec.WriteTagAndValue(output, CatalogName);
      }
      if (DataType != global::protos.DataType.Int) {
        output.WriteRawTag(32);
        output.WriteEnum((int) DataType);
      }
      if (catalogNameForDataTypeList_ != null) {
        _single_catalogNameForDataTypeList_codec.WriteTagAndValue(output, CatalogNameForDataTypeList);
      }
      if (Min != 0D) {
        output.WriteRawTag(49);
        output.WriteDouble(Min);
      }
      if (Max != 0D) {
        output.WriteRawTag(57);
        output.WriteDouble(Max);
      }
      if (Multiple != false) {
        output.WriteRawTag(64);
        output.WriteBool(Multiple);
      }
      filters_.WriteTo(output, _repeated_filters_codec);
      includeFields_.WriteTo(output, _repeated_includeFields_codec);
      options_.WriteTo(output, _repeated_options_codec);
      if (IsRequired != false) {
        output.WriteRawTag(96);
        output.WriteBool(IsRequired);
      }
      if (suffix_ != null) {
        _single_suffix_codec.WriteTagAndValue(output, Suffix);
      }
      if (ordering_ != null) {
        _single_ordering_codec.WriteTagAndValue(output, Ordering);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Caption.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Caption);
      }
      if (catalogName_ != null) {
        _single_catalogName_codec.WriteTagAndValue(ref output, CatalogName);
      }
      if (DataType != global::protos.DataType.Int) {
        output.WriteRawTag(32);
        output.WriteEnum((int) DataType);
      }
      if (catalogNameForDataTypeList_ != null) {
        _single_catalogNameForDataTypeList_codec.WriteTagAndValue(ref output, CatalogNameForDataTypeList);
      }
      if (Min != 0D) {
        output.WriteRawTag(49);
        output.WriteDouble(Min);
      }
      if (Max != 0D) {
        output.WriteRawTag(57);
        output.WriteDouble(Max);
      }
      if (Multiple != false) {
        output.WriteRawTag(64);
        output.WriteBool(Multiple);
      }
      filters_.WriteTo(ref output, _repeated_filters_codec);
      includeFields_.WriteTo(ref output, _repeated_includeFields_codec);
      options_.WriteTo(ref output, _repeated_options_codec);
      if (IsRequired != false) {
        output.WriteRawTag(96);
        output.WriteBool(IsRequired);
      }
      if (suffix_ != null) {
        _single_suffix_codec.WriteTagAndValue(ref output, Suffix);
      }
      if (ordering_ != null) {
        _single_ordering_codec.WriteTagAndValue(ref output, Ordering);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Caption.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Caption);
      }
      if (catalogName_ != null) {
        size += _single_catalogName_codec.CalculateSizeWithTag(CatalogName);
      }
      if (DataType != global::protos.DataType.Int) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) DataType);
      }
      if (catalogNameForDataTypeList_ != null) {
        size += _single_catalogNameForDataTypeList_codec.CalculateSizeWithTag(CatalogNameForDataTypeList);
      }
      if (Min != 0D) {
        size += 1 + 8;
      }
      if (Max != 0D) {
        size += 1 + 8;
      }
      if (Multiple != false) {
        size += 1 + 1;
      }
      size += filters_.CalculateSize(_repeated_filters_codec);
      size += includeFields_.CalculateSize(_repeated_includeFields_codec);
      size += options_.CalculateSize(_repeated_options_codec);
      if (IsRequired != false) {
        size += 1 + 1;
      }
      if (suffix_ != null) {
        size += _single_suffix_codec.CalculateSizeWithTag(Suffix);
      }
      if (ordering_ != null) {
        size += _single_ordering_codec.CalculateSizeWithTag(Ordering);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ExtendPropertyDefine other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Caption.Length != 0) {
        Caption = other.Caption;
      }
      if (other.catalogName_ != null) {
        if (catalogName_ == null || other.CatalogName != "") {
          CatalogName = other.CatalogName;
        }
      }
      if (other.DataType != global::protos.DataType.Int) {
        DataType = other.DataType;
      }
      if (other.catalogNameForDataTypeList_ != null) {
        if (catalogNameForDataTypeList_ == null || other.CatalogNameForDataTypeList != "") {
          CatalogNameForDataTypeList = other.CatalogNameForDataTypeList;
        }
      }
      if (other.Min != 0D) {
        Min = other.Min;
      }
      if (other.Max != 0D) {
        Max = other.Max;
      }
      if (other.Multiple != false) {
        Multiple = other.Multiple;
      }
      filters_.Add(other.filters_);
      includeFields_.Add(other.includeFields_);
      options_.Add(other.options_);
      if (other.IsRequired != false) {
        IsRequired = other.IsRequired;
      }
      if (other.suffix_ != null) {
        if (suffix_ == null || other.Suffix != "") {
          Suffix = other.Suffix;
        }
      }
      if (other.ordering_ != null) {
        if (ordering_ == null || other.Ordering != 0) {
          Ordering = other.Ordering;
        }
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            Caption = input.ReadString();
            break;
          }
          case 26: {
            string value = _single_catalogName_codec.Read(input);
            if (catalogName_ == null || value != "") {
              CatalogName = value;
            }
            break;
          }
          case 32: {
            DataType = (global::protos.DataType) input.ReadEnum();
            break;
          }
          case 42: {
            string value = _single_catalogNameForDataTypeList_codec.Read(input);
            if (catalogNameForDataTypeList_ == null || value != "") {
              CatalogNameForDataTypeList = value;
            }
            break;
          }
          case 49: {
            Min = input.ReadDouble();
            break;
          }
          case 57: {
            Max = input.ReadDouble();
            break;
          }
          case 64: {
            Multiple = input.ReadBool();
            break;
          }
          case 74: {
            filters_.AddEntriesFrom(input, _repeated_filters_codec);
            break;
          }
          case 82: {
            includeFields_.AddEntriesFrom(input, _repeated_includeFields_codec);
            break;
          }
          case 90: {
            options_.AddEntriesFrom(input, _repeated_options_codec);
            break;
          }
          case 96: {
            IsRequired = input.ReadBool();
            break;
          }
          case 106: {
            string value = _single_suffix_codec.Read(input);
            if (suffix_ == null || value != "") {
              Suffix = value;
            }
            break;
          }
          case 114: {
            int? value = _single_ordering_codec.Read(input);
            if (ordering_ == null || value != 0) {
              Ordering = value;
            }
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            Caption = input.ReadString();
            break;
          }
          case 26: {
            string value = _single_catalogName_codec.Read(ref input);
            if (catalogName_ == null || value != "") {
              CatalogName = value;
            }
            break;
          }
          case 32: {
            DataType = (global::protos.DataType) input.ReadEnum();
            break;
          }
          case 42: {
            string value = _single_catalogNameForDataTypeList_codec.Read(ref input);
            if (catalogNameForDataTypeList_ == null || value != "") {
              CatalogNameForDataTypeList = value;
            }
            break;
          }
          case 49: {
            Min = input.ReadDouble();
            break;
          }
          case 57: {
            Max = input.ReadDouble();
            break;
          }
          case 64: {
            Multiple = input.ReadBool();
            break;
          }
          case 74: {
            filters_.AddEntriesFrom(ref input, _repeated_filters_codec);
            break;
          }
          case 82: {
            includeFields_.AddEntriesFrom(ref input, _repeated_includeFields_codec);
            break;
          }
          case 90: {
            options_.AddEntriesFrom(ref input, _repeated_options_codec);
            break;
          }
          case 96: {
            IsRequired = input.ReadBool();
            break;
          }
          case 106: {
            string value = _single_suffix_codec.Read(ref input);
            if (suffix_ == null || value != "") {
              Suffix = value;
            }
            break;
          }
          case 114: {
            int? value = _single_ordering_codec.Read(ref input);
            if (ordering_ == null || value != 0) {
              Ordering = value;
            }
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Option : pb::IMessage<Option>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Option> _parser = new pb::MessageParser<Option>(() => new Option());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Option> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::protos.ExtendedFieldReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Option() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Option(Option other) : this() {
      key_ = other.key_;
      value_ = other.value_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Option Clone() {
      return new Option(this);
    }

    /// <summary>Field number for the "key" field.</summary>
    public const int KeyFieldNumber = 1;
    private string key_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Key {
      get { return key_; }
      set {
        key_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 2;
    private string value_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Value {
      get { return value_; }
      set {
        value_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Option);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Option other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Key != other.Key) return false;
      if (Value != other.Value) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Key.Length != 0) hash ^= Key.GetHashCode();
      if (Value.Length != 0) hash ^= Value.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Key.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Key);
      }
      if (Value.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Value);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Key.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Key);
      }
      if (Value.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Value);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Key.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Key);
      }
      if (Value.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Value);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Option other) {
      if (other == null) {
        return;
      }
      if (other.Key.Length != 0) {
        Key = other.Key;
      }
      if (other.Value.Length != 0) {
        Value = other.Value;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Key = input.ReadString();
            break;
          }
          case 18: {
            Value = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Key = input.ReadString();
            break;
          }
          case 18: {
            Value = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
