// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: LichSuPhanQuyenScope.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace protos {

  /// <summary>Holder for reflection information generated from LichSuPhanQuyenScope.proto</summary>
  public static partial class LichSuPhanQuyenScopeReflection {

    #region Descriptor
    /// <summary>File descriptor for LichSuPhanQuyenScope.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LichSuPhanQuyenScopeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChpMaWNoU3VQaGFuUXV5ZW5TY29wZS5wcm90bxIUTGljaFN1UGhhblF1eWVu",
            "U2NvcGUaHmdvb2dsZS9wcm90b2J1Zi93cmFwcGVycy5wcm90bxofZ29vZ2xl",
            "L3Byb3RvYnVmL3RpbWVzdGFtcC5wcm90byKUBQoUTGljaFN1UGhhblF1eWVu",
            "U2NvcGUSCgoCaWQYASABKAkSIAoYaWRfbmd1b2lfZHVvY19waGFuX3F1eWVu",
            "GAIgASgJEhoKEmlkX25ob21fbmd1b2lfZHVuZxgDIAEoCRIaChJpZF9uZ3Vv",
            "aV90aHVjX2hpZW4YBCABKAkSEgoKbWFfcGhhbl9oZRgFIAEoCRIRCgloYW5o",
            "X2RvbmcYBiABKAkSLQoHZ2hpX2NodRgHIAEoCzIcLmdvb2dsZS5wcm90b2J1",
            "Zi5TdHJpbmdWYWx1ZRIVCg1zY29wZV90eXBlX2N1GAggASgJEhoKEmlkX2Rv",
            "bl92aV9zY29wZV9jdRgJIAEoCRIXCg9pZF9uZ2FuaF9kb2NfY3UYCiADKAkS",
            "MwoPbmdheV9oZXRfaGFuX2N1GAsgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRp",
            "bWVzdGFtcBIcChRpZF9uZ3VvaV91eV9xdXllbl9jdRgMIAEoCRIjChtpZF9k",
            "YW5oX211Y19jaHV5ZW5fbmdhbmhfY3UYDSABKAkSFgoOc2NvcGVfdHlwZV9t",
            "b2kYDiABKAkSGwoTaWRfZG9uX3ZpX3Njb3BlX21vaRgPIAEoCRIYChBpZF9u",
            "Z2FuaF9kb2NfbW9pGBAgAygJEjQKEG5nYXlfaGV0X2hhbl9tb2kYESABKAsy",
            "Gi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEh0KFWlkX25ndW9pX3V5X3F1",
            "eWVuX21vaRgSIAEoCRIkChxpZF9kYW5oX211Y19jaHV5ZW5fbmdhbmhfbW9p",
            "GBMgASgJEjIKDm5nYXlfdGh1Y19oaWVuGBQgASgLMhouZ29vZ2xlLnByb3Rv",
            "YnVmLlRpbWVzdGFtcCK4AgofTGljaFN1UGhhblF1eWVuU2NvcGVMaXN0UmVx",
            "dWVzdBI+ChhpZF9uZ3VvaV9kdW9jX3BoYW5fcXV5ZW4YASABKAsyHC5nb29n",
            "bGUucHJvdG9idWYuU3RyaW5nVmFsdWUSOAoSaWRfbmhvbV9uZ3VvaV9kdW5n",
            "GAIgASgLMhwuZ29vZ2xlLnByb3RvYnVmLlN0cmluZ1ZhbHVlEjgKEmlkX25n",
            "dW9pX3RodWNfaGllbhgDIAEoCzIcLmdvb2dsZS5wcm90b2J1Zi5TdHJpbmdW",
            "YWx1ZRIwCgptYV9waGFuX2hlGAQgASgLMhwuZ29vZ2xlLnByb3RvYnVmLlN0",
            "cmluZ1ZhbHVlEi8KCWhhbmhfZG9uZxgFIAEoCzIcLmdvb2dsZS5wcm90b2J1",
            "Zi5TdHJpbmdWYWx1ZSJ/CiBMaWNoU3VQaGFuUXV5ZW5TY29wZUxpc3RSZXNw",
            "b25zZRI5CgVpdGVtcxgBIAMoCzIqLkxpY2hTdVBoYW5RdXllblNjb3BlLkxp",
            "Y2hTdVBoYW5RdXllblNjb3BlEg8KB3N1Y2Nlc3MYAiABKAgSDwoHbWVzc2Fn",
            "ZRgDIAEoCSIsCh5MaWNoU3VQaGFuUXV5ZW5TY29wZUdldFJlcXVlc3QSCgoC",
            "aWQYASABKAkifQofTGljaFN1UGhhblF1eWVuU2NvcGVHZXRSZXNwb25zZRI4",
            "CgRpdGVtGAEgASgLMiouTGljaFN1UGhhblF1eWVuU2NvcGUuTGljaFN1UGhh",
            "blF1eWVuU2NvcGUSDwoHc3VjY2VzcxgCIAEoCBIPCgdtZXNzYWdlGAMgASgJ",
            "IlsKH0xpY2hTdVBoYW5RdXllblNjb3BlU2F2ZVJlcXVlc3QSOAoEaXRlbRgB",
            "IAEoCzIqLkxpY2hTdVBoYW5RdXllblNjb3BlLkxpY2hTdVBoYW5RdXllblNj",
            "b3BlIlAKIExpY2hTdVBoYW5RdXllblNjb3BlU2F2ZVJlc3BvbnNlEgoKAmlk",
            "GAEgASgJEg8KB3N1Y2Nlc3MYAiABKAgSDwoHbWVzc2FnZRgDIAEoCTKCAwob",
            "TGljaFN1UGhhblF1eWVuU2NvcGVTZXJ2aWNlEngKB0dldExpc3QSNS5MaWNo",
            "U3VQaGFuUXV5ZW5TY29wZS5MaWNoU3VQaGFuUXV5ZW5TY29wZUxpc3RSZXF1",
            "ZXN0GjYuTGljaFN1UGhhblF1eWVuU2NvcGUuTGljaFN1UGhhblF1eWVuU2Nv",
            "cGVMaXN0UmVzcG9uc2UScgoDR2V0EjQuTGljaFN1UGhhblF1eWVuU2NvcGUu",
            "TGljaFN1UGhhblF1eWVuU2NvcGVHZXRSZXF1ZXN0GjUuTGljaFN1UGhhblF1",
            "eWVuU2NvcGUuTGljaFN1UGhhblF1eWVuU2NvcGVHZXRSZXNwb25zZRJ1CgRT",
            "YXZlEjUuTGljaFN1UGhhblF1eWVuU2NvcGUuTGljaFN1UGhhblF1eWVuU2Nv",
            "cGVTYXZlUmVxdWVzdBo2LkxpY2hTdVBoYW5RdXllblNjb3BlLkxpY2hTdVBo",
            "YW5RdXllblNjb3BlU2F2ZVJlc3BvbnNlQgmqAgZwcm90b3NiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::protos.LichSuPhanQuyenScope), global::protos.LichSuPhanQuyenScope.Parser, new[]{ "Id", "IdNguoiDuocPhanQuyen", "IdNhomNguoiDung", "IdNguoiThucHien", "MaPhanHe", "HanhDong", "GhiChu", "ScopeTypeCu", "IdDonViScopeCu", "IdNganhDocCu", "NgayHetHanCu", "IdNguoiUyQuyenCu", "IdDanhMucChuyenNganhCu", "ScopeTypeMoi", "IdDonViScopeMoi", "IdNganhDocMoi", "NgayHetHanMoi", "IdNguoiUyQuyenMoi", "IdDanhMucChuyenNganhMoi", "NgayThucHien" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::protos.LichSuPhanQuyenScopeListRequest), global::protos.LichSuPhanQuyenScopeListRequest.Parser, new[]{ "IdNguoiDuocPhanQuyen", "IdNhomNguoiDung", "IdNguoiThucHien", "MaPhanHe", "HanhDong" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::protos.LichSuPhanQuyenScopeListResponse), global::protos.LichSuPhanQuyenScopeListResponse.Parser, new[]{ "Items", "Success", "Message" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::protos.LichSuPhanQuyenScopeGetRequest), global::protos.LichSuPhanQuyenScopeGetRequest.Parser, new[]{ "Id" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::protos.LichSuPhanQuyenScopeGetResponse), global::protos.LichSuPhanQuyenScopeGetResponse.Parser, new[]{ "Item", "Success", "Message" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::protos.LichSuPhanQuyenScopeSaveRequest), global::protos.LichSuPhanQuyenScopeSaveRequest.Parser, new[]{ "Item" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::protos.LichSuPhanQuyenScopeSaveResponse), global::protos.LichSuPhanQuyenScopeSaveResponse.Parser, new[]{ "Id", "Success", "Message" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LichSuPhanQuyenScope : pb::IMessage<LichSuPhanQuyenScope>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LichSuPhanQuyenScope> _parser = new pb::MessageParser<LichSuPhanQuyenScope>(() => new LichSuPhanQuyenScope());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LichSuPhanQuyenScope> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::protos.LichSuPhanQuyenScopeReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LichSuPhanQuyenScope() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LichSuPhanQuyenScope(LichSuPhanQuyenScope other) : this() {
      id_ = other.id_;
      idNguoiDuocPhanQuyen_ = other.idNguoiDuocPhanQuyen_;
      idNhomNguoiDung_ = other.idNhomNguoiDung_;
      idNguoiThucHien_ = other.idNguoiThucHien_;
      maPhanHe_ = other.maPhanHe_;
      hanhDong_ = other.hanhDong_;
      GhiChu = other.GhiChu;
      scopeTypeCu_ = other.scopeTypeCu_;
      idDonViScopeCu_ = other.idDonViScopeCu_;
      idNganhDocCu_ = other.idNganhDocCu_.Clone();
      ngayHetHanCu_ = other.ngayHetHanCu_ != null ? other.ngayHetHanCu_.Clone() : null;
      idNguoiUyQuyenCu_ = other.idNguoiUyQuyenCu_;
      idDanhMucChuyenNganhCu_ = other.idDanhMucChuyenNganhCu_;
      scopeTypeMoi_ = other.scopeTypeMoi_;
      idDonViScopeMoi_ = other.idDonViScopeMoi_;
      idNganhDocMoi_ = other.idNganhDocMoi_.Clone();
      ngayHetHanMoi_ = other.ngayHetHanMoi_ != null ? other.ngayHetHanMoi_.Clone() : null;
      idNguoiUyQuyenMoi_ = other.idNguoiUyQuyenMoi_;
      idDanhMucChuyenNganhMoi_ = other.idDanhMucChuyenNganhMoi_;
      ngayThucHien_ = other.ngayThucHien_ != null ? other.ngayThucHien_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LichSuPhanQuyenScope Clone() {
      return new LichSuPhanQuyenScope(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "id_nguoi_duoc_phan_quyen" field.</summary>
    public const int IdNguoiDuocPhanQuyenFieldNumber = 2;
    private string idNguoiDuocPhanQuyen_ = "";
    /// <summary>
    /// Người được phân quyền
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string IdNguoiDuocPhanQuyen {
      get { return idNguoiDuocPhanQuyen_; }
      set {
        idNguoiDuocPhanQuyen_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "id_nhom_nguoi_dung" field.</summary>
    public const int IdNhomNguoiDungFieldNumber = 3;
    private string idNhomNguoiDung_ = "";
    /// <summary>
    /// Nhóm người dùng (nếu có)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string IdNhomNguoiDung {
      get { return idNhomNguoiDung_; }
      set {
        idNhomNguoiDung_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "id_nguoi_thuc_hien" field.</summary>
    public const int IdNguoiThucHienFieldNumber = 4;
    private string idNguoiThucHien_ = "";
    /// <summary>
    /// Người thực hiện thay đổi
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string IdNguoiThucHien {
      get { return idNguoiThucHien_; }
      set {
        idNguoiThucHien_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ma_phan_he" field.</summary>
    public const int MaPhanHeFieldNumber = 5;
    private string maPhanHe_ = "";
    /// <summary>
    /// Phân hệ
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MaPhanHe {
      get { return maPhanHe_; }
      set {
        maPhanHe_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "hanh_dong" field.</summary>
    public const int HanhDongFieldNumber = 6;
    private string hanhDong_ = "";
    /// <summary>
    /// Hành động
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string HanhDong {
      get { return hanhDong_; }
      set {
        hanhDong_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ghi_chu" field.</summary>
    public const int GhiChuFieldNumber = 7;
    private static readonly pb::FieldCodec<string> _single_ghiChu_codec = pb::FieldCodec.ForClassWrapper<string>(58);
    private string ghiChu_;
    /// <summary>
    /// Ghi chú
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GhiChu {
      get { return ghiChu_; }
      set {
        ghiChu_ = value;
      }
    }


    /// <summary>Field number for the "scope_type_cu" field.</summary>
    public const int ScopeTypeCuFieldNumber = 8;
    private string scopeTypeCu_ = "";
    /// <summary>
    /// --- Scope cũ ---
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ScopeTypeCu {
      get { return scopeTypeCu_; }
      set {
        scopeTypeCu_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "id_don_vi_scope_cu" field.</summary>
    public const int IdDonViScopeCuFieldNumber = 9;
    private string idDonViScopeCu_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string IdDonViScopeCu {
      get { return idDonViScopeCu_; }
      set {
        idDonViScopeCu_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "id_nganh_doc_cu" field.</summary>
    public const int IdNganhDocCuFieldNumber = 10;
    private static readonly pb::FieldCodec<string> _repeated_idNganhDocCu_codec
        = pb::FieldCodec.ForString(82);
    private readonly pbc::RepeatedField<string> idNganhDocCu_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> IdNganhDocCu {
      get { return idNganhDocCu_; }
    }

    /// <summary>Field number for the "ngay_het_han_cu" field.</summary>
    public const int NgayHetHanCuFieldNumber = 11;
    private global::Google.Protobuf.WellKnownTypes.Timestamp ngayHetHanCu_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp NgayHetHanCu {
      get { return ngayHetHanCu_; }
      set {
        ngayHetHanCu_ = value;
      }
    }

    /// <summary>Field number for the "id_nguoi_uy_quyen_cu" field.</summary>
    public const int IdNguoiUyQuyenCuFieldNumber = 12;
    private string idNguoiUyQuyenCu_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string IdNguoiUyQuyenCu {
      get { return idNguoiUyQuyenCu_; }
      set {
        idNguoiUyQuyenCu_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "id_danh_muc_chuyen_nganh_cu" field.</summary>
    public const int IdDanhMucChuyenNganhCuFieldNumber = 13;
    private string idDanhMucChuyenNganhCu_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string IdDanhMucChuyenNganhCu {
      get { return idDanhMucChuyenNganhCu_; }
      set {
        idDanhMucChuyenNganhCu_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "scope_type_moi" field.</summary>
    public const int ScopeTypeMoiFieldNumber = 14;
    private string scopeTypeMoi_ = "";
    /// <summary>
    /// --- Scope mới ---
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ScopeTypeMoi {
      get { return scopeTypeMoi_; }
      set {
        scopeTypeMoi_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "id_don_vi_scope_moi" field.</summary>
    public const int IdDonViScopeMoiFieldNumber = 15;
    private string idDonViScopeMoi_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string IdDonViScopeMoi {
      get { return idDonViScopeMoi_; }
      set {
        idDonViScopeMoi_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "id_nganh_doc_moi" field.</summary>
    public const int IdNganhDocMoiFieldNumber = 16;
    private static readonly pb::FieldCodec<string> _repeated_idNganhDocMoi_codec
        = pb::FieldCodec.ForString(130);
    private readonly pbc::RepeatedField<string> idNganhDocMoi_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> IdNganhDocMoi {
      get { return idNganhDocMoi_; }
    }

    /// <summary>Field number for the "ngay_het_han_moi" field.</summary>
    public const int NgayHetHanMoiFieldNumber = 17;
    private global::Google.Protobuf.WellKnownTypes.Timestamp ngayHetHanMoi_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp NgayHetHanMoi {
      get { return ngayHetHanMoi_; }
      set {
        ngayHetHanMoi_ = value;
      }
    }

    /// <summary>Field number for the "id_nguoi_uy_quyen_moi" field.</summary>
    public const int IdNguoiUyQuyenMoiFieldNumber = 18;
    private string idNguoiUyQuyenMoi_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string IdNguoiUyQuyenMoi {
      get { return idNguoiUyQuyenMoi_; }
      set {
        idNguoiUyQuyenMoi_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "id_danh_muc_chuyen_nganh_moi" field.</summary>
    public const int IdDanhMucChuyenNganhMoiFieldNumber = 19;
    private string idDanhMucChuyenNganhMoi_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string IdDanhMucChuyenNganhMoi {
      get { return idDanhMucChuyenNganhMoi_; }
      set {
        idDanhMucChuyenNganhMoi_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ngay_thuc_hien" field.</summary>
    public const int NgayThucHienFieldNumber = 20;
    private global::Google.Protobuf.WellKnownTypes.Timestamp ngayThucHien_;
    /// <summary>
    /// Thời gian thực hiện
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp NgayThucHien {
      get { return ngayThucHien_; }
      set {
        ngayThucHien_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LichSuPhanQuyenScope);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LichSuPhanQuyenScope other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (IdNguoiDuocPhanQuyen != other.IdNguoiDuocPhanQuyen) return false;
      if (IdNhomNguoiDung != other.IdNhomNguoiDung) return false;
      if (IdNguoiThucHien != other.IdNguoiThucHien) return false;
      if (MaPhanHe != other.MaPhanHe) return false;
      if (HanhDong != other.HanhDong) return false;
      if (GhiChu != other.GhiChu) return false;
      if (ScopeTypeCu != other.ScopeTypeCu) return false;
      if (IdDonViScopeCu != other.IdDonViScopeCu) return false;
      if(!idNganhDocCu_.Equals(other.idNganhDocCu_)) return false;
      if (!object.Equals(NgayHetHanCu, other.NgayHetHanCu)) return false;
      if (IdNguoiUyQuyenCu != other.IdNguoiUyQuyenCu) return false;
      if (IdDanhMucChuyenNganhCu != other.IdDanhMucChuyenNganhCu) return false;
      if (ScopeTypeMoi != other.ScopeTypeMoi) return false;
      if (IdDonViScopeMoi != other.IdDonViScopeMoi) return false;
      if(!idNganhDocMoi_.Equals(other.idNganhDocMoi_)) return false;
      if (!object.Equals(NgayHetHanMoi, other.NgayHetHanMoi)) return false;
      if (IdNguoiUyQuyenMoi != other.IdNguoiUyQuyenMoi) return false;
      if (IdDanhMucChuyenNganhMoi != other.IdDanhMucChuyenNganhMoi) return false;
      if (!object.Equals(NgayThucHien, other.NgayThucHien)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (IdNguoiDuocPhanQuyen.Length != 0) hash ^= IdNguoiDuocPhanQuyen.GetHashCode();
      if (IdNhomNguoiDung.Length != 0) hash ^= IdNhomNguoiDung.GetHashCode();
      if (IdNguoiThucHien.Length != 0) hash ^= IdNguoiThucHien.GetHashCode();
      if (MaPhanHe.Length != 0) hash ^= MaPhanHe.GetHashCode();
      if (HanhDong.Length != 0) hash ^= HanhDong.GetHashCode();
      if (ghiChu_ != null) hash ^= GhiChu.GetHashCode();
      if (ScopeTypeCu.Length != 0) hash ^= ScopeTypeCu.GetHashCode();
      if (IdDonViScopeCu.Length != 0) hash ^= IdDonViScopeCu.GetHashCode();
      hash ^= idNganhDocCu_.GetHashCode();
      if (ngayHetHanCu_ != null) hash ^= NgayHetHanCu.GetHashCode();
      if (IdNguoiUyQuyenCu.Length != 0) hash ^= IdNguoiUyQuyenCu.GetHashCode();
      if (IdDanhMucChuyenNganhCu.Length != 0) hash ^= IdDanhMucChuyenNganhCu.GetHashCode();
      if (ScopeTypeMoi.Length != 0) hash ^= ScopeTypeMoi.GetHashCode();
      if (IdDonViScopeMoi.Length != 0) hash ^= IdDonViScopeMoi.GetHashCode();
      hash ^= idNganhDocMoi_.GetHashCode();
      if (ngayHetHanMoi_ != null) hash ^= NgayHetHanMoi.GetHashCode();
      if (IdNguoiUyQuyenMoi.Length != 0) hash ^= IdNguoiUyQuyenMoi.GetHashCode();
      if (IdDanhMucChuyenNganhMoi.Length != 0) hash ^= IdDanhMucChuyenNganhMoi.GetHashCode();
      if (ngayThucHien_ != null) hash ^= NgayThucHien.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (IdNguoiDuocPhanQuyen.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(IdNguoiDuocPhanQuyen);
      }
      if (IdNhomNguoiDung.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(IdNhomNguoiDung);
      }
      if (IdNguoiThucHien.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(IdNguoiThucHien);
      }
      if (MaPhanHe.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(MaPhanHe);
      }
      if (HanhDong.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(HanhDong);
      }
      if (ghiChu_ != null) {
        _single_ghiChu_codec.WriteTagAndValue(output, GhiChu);
      }
      if (ScopeTypeCu.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(ScopeTypeCu);
      }
      if (IdDonViScopeCu.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(IdDonViScopeCu);
      }
      idNganhDocCu_.WriteTo(output, _repeated_idNganhDocCu_codec);
      if (ngayHetHanCu_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(NgayHetHanCu);
      }
      if (IdNguoiUyQuyenCu.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(IdNguoiUyQuyenCu);
      }
      if (IdDanhMucChuyenNganhCu.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(IdDanhMucChuyenNganhCu);
      }
      if (ScopeTypeMoi.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(ScopeTypeMoi);
      }
      if (IdDonViScopeMoi.Length != 0) {
        output.WriteRawTag(122);
        output.WriteString(IdDonViScopeMoi);
      }
      idNganhDocMoi_.WriteTo(output, _repeated_idNganhDocMoi_codec);
      if (ngayHetHanMoi_ != null) {
        output.WriteRawTag(138, 1);
        output.WriteMessage(NgayHetHanMoi);
      }
      if (IdNguoiUyQuyenMoi.Length != 0) {
        output.WriteRawTag(146, 1);
        output.WriteString(IdNguoiUyQuyenMoi);
      }
      if (IdDanhMucChuyenNganhMoi.Length != 0) {
        output.WriteRawTag(154, 1);
        output.WriteString(IdDanhMucChuyenNganhMoi);
      }
      if (ngayThucHien_ != null) {
        output.WriteRawTag(162, 1);
        output.WriteMessage(NgayThucHien);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (IdNguoiDuocPhanQuyen.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(IdNguoiDuocPhanQuyen);
      }
      if (IdNhomNguoiDung.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(IdNhomNguoiDung);
      }
      if (IdNguoiThucHien.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(IdNguoiThucHien);
      }
      if (MaPhanHe.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(MaPhanHe);
      }
      if (HanhDong.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(HanhDong);
      }
      if (ghiChu_ != null) {
        _single_ghiChu_codec.WriteTagAndValue(ref output, GhiChu);
      }
      if (ScopeTypeCu.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(ScopeTypeCu);
      }
      if (IdDonViScopeCu.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(IdDonViScopeCu);
      }
      idNganhDocCu_.WriteTo(ref output, _repeated_idNganhDocCu_codec);
      if (ngayHetHanCu_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(NgayHetHanCu);
      }
      if (IdNguoiUyQuyenCu.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(IdNguoiUyQuyenCu);
      }
      if (IdDanhMucChuyenNganhCu.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(IdDanhMucChuyenNganhCu);
      }
      if (ScopeTypeMoi.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(ScopeTypeMoi);
      }
      if (IdDonViScopeMoi.Length != 0) {
        output.WriteRawTag(122);
        output.WriteString(IdDonViScopeMoi);
      }
      idNganhDocMoi_.WriteTo(ref output, _repeated_idNganhDocMoi_codec);
      if (ngayHetHanMoi_ != null) {
        output.WriteRawTag(138, 1);
        output.WriteMessage(NgayHetHanMoi);
      }
      if (IdNguoiUyQuyenMoi.Length != 0) {
        output.WriteRawTag(146, 1);
        output.WriteString(IdNguoiUyQuyenMoi);
      }
      if (IdDanhMucChuyenNganhMoi.Length != 0) {
        output.WriteRawTag(154, 1);
        output.WriteString(IdDanhMucChuyenNganhMoi);
      }
      if (ngayThucHien_ != null) {
        output.WriteRawTag(162, 1);
        output.WriteMessage(NgayThucHien);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (IdNguoiDuocPhanQuyen.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdNguoiDuocPhanQuyen);
      }
      if (IdNhomNguoiDung.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdNhomNguoiDung);
      }
      if (IdNguoiThucHien.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdNguoiThucHien);
      }
      if (MaPhanHe.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MaPhanHe);
      }
      if (HanhDong.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(HanhDong);
      }
      if (ghiChu_ != null) {
        size += _single_ghiChu_codec.CalculateSizeWithTag(GhiChu);
      }
      if (ScopeTypeCu.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ScopeTypeCu);
      }
      if (IdDonViScopeCu.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdDonViScopeCu);
      }
      size += idNganhDocCu_.CalculateSize(_repeated_idNganhDocCu_codec);
      if (ngayHetHanCu_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(NgayHetHanCu);
      }
      if (IdNguoiUyQuyenCu.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdNguoiUyQuyenCu);
      }
      if (IdDanhMucChuyenNganhCu.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdDanhMucChuyenNganhCu);
      }
      if (ScopeTypeMoi.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ScopeTypeMoi);
      }
      if (IdDonViScopeMoi.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdDonViScopeMoi);
      }
      size += idNganhDocMoi_.CalculateSize(_repeated_idNganhDocMoi_codec);
      if (ngayHetHanMoi_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(NgayHetHanMoi);
      }
      if (IdNguoiUyQuyenMoi.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(IdNguoiUyQuyenMoi);
      }
      if (IdDanhMucChuyenNganhMoi.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(IdDanhMucChuyenNganhMoi);
      }
      if (ngayThucHien_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(NgayThucHien);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LichSuPhanQuyenScope other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.IdNguoiDuocPhanQuyen.Length != 0) {
        IdNguoiDuocPhanQuyen = other.IdNguoiDuocPhanQuyen;
      }
      if (other.IdNhomNguoiDung.Length != 0) {
        IdNhomNguoiDung = other.IdNhomNguoiDung;
      }
      if (other.IdNguoiThucHien.Length != 0) {
        IdNguoiThucHien = other.IdNguoiThucHien;
      }
      if (other.MaPhanHe.Length != 0) {
        MaPhanHe = other.MaPhanHe;
      }
      if (other.HanhDong.Length != 0) {
        HanhDong = other.HanhDong;
      }
      if (other.ghiChu_ != null) {
        if (ghiChu_ == null || other.GhiChu != "") {
          GhiChu = other.GhiChu;
        }
      }
      if (other.ScopeTypeCu.Length != 0) {
        ScopeTypeCu = other.ScopeTypeCu;
      }
      if (other.IdDonViScopeCu.Length != 0) {
        IdDonViScopeCu = other.IdDonViScopeCu;
      }
      idNganhDocCu_.Add(other.idNganhDocCu_);
      if (other.ngayHetHanCu_ != null) {
        if (ngayHetHanCu_ == null) {
          NgayHetHanCu = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        NgayHetHanCu.MergeFrom(other.NgayHetHanCu);
      }
      if (other.IdNguoiUyQuyenCu.Length != 0) {
        IdNguoiUyQuyenCu = other.IdNguoiUyQuyenCu;
      }
      if (other.IdDanhMucChuyenNganhCu.Length != 0) {
        IdDanhMucChuyenNganhCu = other.IdDanhMucChuyenNganhCu;
      }
      if (other.ScopeTypeMoi.Length != 0) {
        ScopeTypeMoi = other.ScopeTypeMoi;
      }
      if (other.IdDonViScopeMoi.Length != 0) {
        IdDonViScopeMoi = other.IdDonViScopeMoi;
      }
      idNganhDocMoi_.Add(other.idNganhDocMoi_);
      if (other.ngayHetHanMoi_ != null) {
        if (ngayHetHanMoi_ == null) {
          NgayHetHanMoi = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        NgayHetHanMoi.MergeFrom(other.NgayHetHanMoi);
      }
      if (other.IdNguoiUyQuyenMoi.Length != 0) {
        IdNguoiUyQuyenMoi = other.IdNguoiUyQuyenMoi;
      }
      if (other.IdDanhMucChuyenNganhMoi.Length != 0) {
        IdDanhMucChuyenNganhMoi = other.IdDanhMucChuyenNganhMoi;
      }
      if (other.ngayThucHien_ != null) {
        if (ngayThucHien_ == null) {
          NgayThucHien = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        NgayThucHien.MergeFrom(other.NgayThucHien);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            IdNguoiDuocPhanQuyen = input.ReadString();
            break;
          }
          case 26: {
            IdNhomNguoiDung = input.ReadString();
            break;
          }
          case 34: {
            IdNguoiThucHien = input.ReadString();
            break;
          }
          case 42: {
            MaPhanHe = input.ReadString();
            break;
          }
          case 50: {
            HanhDong = input.ReadString();
            break;
          }
          case 58: {
            string value = _single_ghiChu_codec.Read(input);
            if (ghiChu_ == null || value != "") {
              GhiChu = value;
            }
            break;
          }
          case 66: {
            ScopeTypeCu = input.ReadString();
            break;
          }
          case 74: {
            IdDonViScopeCu = input.ReadString();
            break;
          }
          case 82: {
            idNganhDocCu_.AddEntriesFrom(input, _repeated_idNganhDocCu_codec);
            break;
          }
          case 90: {
            if (ngayHetHanCu_ == null) {
              NgayHetHanCu = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(NgayHetHanCu);
            break;
          }
          case 98: {
            IdNguoiUyQuyenCu = input.ReadString();
            break;
          }
          case 106: {
            IdDanhMucChuyenNganhCu = input.ReadString();
            break;
          }
          case 114: {
            ScopeTypeMoi = input.ReadString();
            break;
          }
          case 122: {
            IdDonViScopeMoi = input.ReadString();
            break;
          }
          case 130: {
            idNganhDocMoi_.AddEntriesFrom(input, _repeated_idNganhDocMoi_codec);
            break;
          }
          case 138: {
            if (ngayHetHanMoi_ == null) {
              NgayHetHanMoi = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(NgayHetHanMoi);
            break;
          }
          case 146: {
            IdNguoiUyQuyenMoi = input.ReadString();
            break;
          }
          case 154: {
            IdDanhMucChuyenNganhMoi = input.ReadString();
            break;
          }
          case 162: {
            if (ngayThucHien_ == null) {
              NgayThucHien = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(NgayThucHien);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            IdNguoiDuocPhanQuyen = input.ReadString();
            break;
          }
          case 26: {
            IdNhomNguoiDung = input.ReadString();
            break;
          }
          case 34: {
            IdNguoiThucHien = input.ReadString();
            break;
          }
          case 42: {
            MaPhanHe = input.ReadString();
            break;
          }
          case 50: {
            HanhDong = input.ReadString();
            break;
          }
          case 58: {
            string value = _single_ghiChu_codec.Read(ref input);
            if (ghiChu_ == null || value != "") {
              GhiChu = value;
            }
            break;
          }
          case 66: {
            ScopeTypeCu = input.ReadString();
            break;
          }
          case 74: {
            IdDonViScopeCu = input.ReadString();
            break;
          }
          case 82: {
            idNganhDocCu_.AddEntriesFrom(ref input, _repeated_idNganhDocCu_codec);
            break;
          }
          case 90: {
            if (ngayHetHanCu_ == null) {
              NgayHetHanCu = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(NgayHetHanCu);
            break;
          }
          case 98: {
            IdNguoiUyQuyenCu = input.ReadString();
            break;
          }
          case 106: {
            IdDanhMucChuyenNganhCu = input.ReadString();
            break;
          }
          case 114: {
            ScopeTypeMoi = input.ReadString();
            break;
          }
          case 122: {
            IdDonViScopeMoi = input.ReadString();
            break;
          }
          case 130: {
            idNganhDocMoi_.AddEntriesFrom(ref input, _repeated_idNganhDocMoi_codec);
            break;
          }
          case 138: {
            if (ngayHetHanMoi_ == null) {
              NgayHetHanMoi = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(NgayHetHanMoi);
            break;
          }
          case 146: {
            IdNguoiUyQuyenMoi = input.ReadString();
            break;
          }
          case 154: {
            IdDanhMucChuyenNganhMoi = input.ReadString();
            break;
          }
          case 162: {
            if (ngayThucHien_ == null) {
              NgayThucHien = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(NgayThucHien);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LichSuPhanQuyenScopeListRequest : pb::IMessage<LichSuPhanQuyenScopeListRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LichSuPhanQuyenScopeListRequest> _parser = new pb::MessageParser<LichSuPhanQuyenScopeListRequest>(() => new LichSuPhanQuyenScopeListRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LichSuPhanQuyenScopeListRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::protos.LichSuPhanQuyenScopeReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LichSuPhanQuyenScopeListRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LichSuPhanQuyenScopeListRequest(LichSuPhanQuyenScopeListRequest other) : this() {
      IdNguoiDuocPhanQuyen = other.IdNguoiDuocPhanQuyen;
      IdNhomNguoiDung = other.IdNhomNguoiDung;
      IdNguoiThucHien = other.IdNguoiThucHien;
      MaPhanHe = other.MaPhanHe;
      HanhDong = other.HanhDong;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LichSuPhanQuyenScopeListRequest Clone() {
      return new LichSuPhanQuyenScopeListRequest(this);
    }

    /// <summary>Field number for the "id_nguoi_duoc_phan_quyen" field.</summary>
    public const int IdNguoiDuocPhanQuyenFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _single_idNguoiDuocPhanQuyen_codec = pb::FieldCodec.ForClassWrapper<string>(10);
    private string idNguoiDuocPhanQuyen_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string IdNguoiDuocPhanQuyen {
      get { return idNguoiDuocPhanQuyen_; }
      set {
        idNguoiDuocPhanQuyen_ = value;
      }
    }


    /// <summary>Field number for the "id_nhom_nguoi_dung" field.</summary>
    public const int IdNhomNguoiDungFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _single_idNhomNguoiDung_codec = pb::FieldCodec.ForClassWrapper<string>(18);
    private string idNhomNguoiDung_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string IdNhomNguoiDung {
      get { return idNhomNguoiDung_; }
      set {
        idNhomNguoiDung_ = value;
      }
    }


    /// <summary>Field number for the "id_nguoi_thuc_hien" field.</summary>
    public const int IdNguoiThucHienFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _single_idNguoiThucHien_codec = pb::FieldCodec.ForClassWrapper<string>(26);
    private string idNguoiThucHien_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string IdNguoiThucHien {
      get { return idNguoiThucHien_; }
      set {
        idNguoiThucHien_ = value;
      }
    }


    /// <summary>Field number for the "ma_phan_he" field.</summary>
    public const int MaPhanHeFieldNumber = 4;
    private static readonly pb::FieldCodec<string> _single_maPhanHe_codec = pb::FieldCodec.ForClassWrapper<string>(34);
    private string maPhanHe_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MaPhanHe {
      get { return maPhanHe_; }
      set {
        maPhanHe_ = value;
      }
    }


    /// <summary>Field number for the "hanh_dong" field.</summary>
    public const int HanhDongFieldNumber = 5;
    private static readonly pb::FieldCodec<string> _single_hanhDong_codec = pb::FieldCodec.ForClassWrapper<string>(42);
    private string hanhDong_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string HanhDong {
      get { return hanhDong_; }
      set {
        hanhDong_ = value;
      }
    }


    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LichSuPhanQuyenScopeListRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LichSuPhanQuyenScopeListRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IdNguoiDuocPhanQuyen != other.IdNguoiDuocPhanQuyen) return false;
      if (IdNhomNguoiDung != other.IdNhomNguoiDung) return false;
      if (IdNguoiThucHien != other.IdNguoiThucHien) return false;
      if (MaPhanHe != other.MaPhanHe) return false;
      if (HanhDong != other.HanhDong) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (idNguoiDuocPhanQuyen_ != null) hash ^= IdNguoiDuocPhanQuyen.GetHashCode();
      if (idNhomNguoiDung_ != null) hash ^= IdNhomNguoiDung.GetHashCode();
      if (idNguoiThucHien_ != null) hash ^= IdNguoiThucHien.GetHashCode();
      if (maPhanHe_ != null) hash ^= MaPhanHe.GetHashCode();
      if (hanhDong_ != null) hash ^= HanhDong.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (idNguoiDuocPhanQuyen_ != null) {
        _single_idNguoiDuocPhanQuyen_codec.WriteTagAndValue(output, IdNguoiDuocPhanQuyen);
      }
      if (idNhomNguoiDung_ != null) {
        _single_idNhomNguoiDung_codec.WriteTagAndValue(output, IdNhomNguoiDung);
      }
      if (idNguoiThucHien_ != null) {
        _single_idNguoiThucHien_codec.WriteTagAndValue(output, IdNguoiThucHien);
      }
      if (maPhanHe_ != null) {
        _single_maPhanHe_codec.WriteTagAndValue(output, MaPhanHe);
      }
      if (hanhDong_ != null) {
        _single_hanhDong_codec.WriteTagAndValue(output, HanhDong);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (idNguoiDuocPhanQuyen_ != null) {
        _single_idNguoiDuocPhanQuyen_codec.WriteTagAndValue(ref output, IdNguoiDuocPhanQuyen);
      }
      if (idNhomNguoiDung_ != null) {
        _single_idNhomNguoiDung_codec.WriteTagAndValue(ref output, IdNhomNguoiDung);
      }
      if (idNguoiThucHien_ != null) {
        _single_idNguoiThucHien_codec.WriteTagAndValue(ref output, IdNguoiThucHien);
      }
      if (maPhanHe_ != null) {
        _single_maPhanHe_codec.WriteTagAndValue(ref output, MaPhanHe);
      }
      if (hanhDong_ != null) {
        _single_hanhDong_codec.WriteTagAndValue(ref output, HanhDong);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (idNguoiDuocPhanQuyen_ != null) {
        size += _single_idNguoiDuocPhanQuyen_codec.CalculateSizeWithTag(IdNguoiDuocPhanQuyen);
      }
      if (idNhomNguoiDung_ != null) {
        size += _single_idNhomNguoiDung_codec.CalculateSizeWithTag(IdNhomNguoiDung);
      }
      if (idNguoiThucHien_ != null) {
        size += _single_idNguoiThucHien_codec.CalculateSizeWithTag(IdNguoiThucHien);
      }
      if (maPhanHe_ != null) {
        size += _single_maPhanHe_codec.CalculateSizeWithTag(MaPhanHe);
      }
      if (hanhDong_ != null) {
        size += _single_hanhDong_codec.CalculateSizeWithTag(HanhDong);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LichSuPhanQuyenScopeListRequest other) {
      if (other == null) {
        return;
      }
      if (other.idNguoiDuocPhanQuyen_ != null) {
        if (idNguoiDuocPhanQuyen_ == null || other.IdNguoiDuocPhanQuyen != "") {
          IdNguoiDuocPhanQuyen = other.IdNguoiDuocPhanQuyen;
        }
      }
      if (other.idNhomNguoiDung_ != null) {
        if (idNhomNguoiDung_ == null || other.IdNhomNguoiDung != "") {
          IdNhomNguoiDung = other.IdNhomNguoiDung;
        }
      }
      if (other.idNguoiThucHien_ != null) {
        if (idNguoiThucHien_ == null || other.IdNguoiThucHien != "") {
          IdNguoiThucHien = other.IdNguoiThucHien;
        }
      }
      if (other.maPhanHe_ != null) {
        if (maPhanHe_ == null || other.MaPhanHe != "") {
          MaPhanHe = other.MaPhanHe;
        }
      }
      if (other.hanhDong_ != null) {
        if (hanhDong_ == null || other.HanhDong != "") {
          HanhDong = other.HanhDong;
        }
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            string value = _single_idNguoiDuocPhanQuyen_codec.Read(input);
            if (idNguoiDuocPhanQuyen_ == null || value != "") {
              IdNguoiDuocPhanQuyen = value;
            }
            break;
          }
          case 18: {
            string value = _single_idNhomNguoiDung_codec.Read(input);
            if (idNhomNguoiDung_ == null || value != "") {
              IdNhomNguoiDung = value;
            }
            break;
          }
          case 26: {
            string value = _single_idNguoiThucHien_codec.Read(input);
            if (idNguoiThucHien_ == null || value != "") {
              IdNguoiThucHien = value;
            }
            break;
          }
          case 34: {
            string value = _single_maPhanHe_codec.Read(input);
            if (maPhanHe_ == null || value != "") {
              MaPhanHe = value;
            }
            break;
          }
          case 42: {
            string value = _single_hanhDong_codec.Read(input);
            if (hanhDong_ == null || value != "") {
              HanhDong = value;
            }
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            string value = _single_idNguoiDuocPhanQuyen_codec.Read(ref input);
            if (idNguoiDuocPhanQuyen_ == null || value != "") {
              IdNguoiDuocPhanQuyen = value;
            }
            break;
          }
          case 18: {
            string value = _single_idNhomNguoiDung_codec.Read(ref input);
            if (idNhomNguoiDung_ == null || value != "") {
              IdNhomNguoiDung = value;
            }
            break;
          }
          case 26: {
            string value = _single_idNguoiThucHien_codec.Read(ref input);
            if (idNguoiThucHien_ == null || value != "") {
              IdNguoiThucHien = value;
            }
            break;
          }
          case 34: {
            string value = _single_maPhanHe_codec.Read(ref input);
            if (maPhanHe_ == null || value != "") {
              MaPhanHe = value;
            }
            break;
          }
          case 42: {
            string value = _single_hanhDong_codec.Read(ref input);
            if (hanhDong_ == null || value != "") {
              HanhDong = value;
            }
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LichSuPhanQuyenScopeListResponse : pb::IMessage<LichSuPhanQuyenScopeListResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LichSuPhanQuyenScopeListResponse> _parser = new pb::MessageParser<LichSuPhanQuyenScopeListResponse>(() => new LichSuPhanQuyenScopeListResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LichSuPhanQuyenScopeListResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::protos.LichSuPhanQuyenScopeReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LichSuPhanQuyenScopeListResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LichSuPhanQuyenScopeListResponse(LichSuPhanQuyenScopeListResponse other) : this() {
      items_ = other.items_.Clone();
      success_ = other.success_;
      message_ = other.message_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LichSuPhanQuyenScopeListResponse Clone() {
      return new LichSuPhanQuyenScopeListResponse(this);
    }

    /// <summary>Field number for the "items" field.</summary>
    public const int ItemsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::protos.LichSuPhanQuyenScope> _repeated_items_codec
        = pb::FieldCodec.ForMessage(10, global::protos.LichSuPhanQuyenScope.Parser);
    private readonly pbc::RepeatedField<global::protos.LichSuPhanQuyenScope> items_ = new pbc::RepeatedField<global::protos.LichSuPhanQuyenScope>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::protos.LichSuPhanQuyenScope> Items {
      get { return items_; }
    }

    /// <summary>Field number for the "success" field.</summary>
    public const int SuccessFieldNumber = 2;
    private bool success_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Success {
      get { return success_; }
      set {
        success_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 3;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LichSuPhanQuyenScopeListResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LichSuPhanQuyenScopeListResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!items_.Equals(other.items_)) return false;
      if (Success != other.Success) return false;
      if (Message != other.Message) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= items_.GetHashCode();
      if (Success != false) hash ^= Success.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      items_.WriteTo(output, _repeated_items_codec);
      if (Success != false) {
        output.WriteRawTag(16);
        output.WriteBool(Success);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      items_.WriteTo(ref output, _repeated_items_codec);
      if (Success != false) {
        output.WriteRawTag(16);
        output.WriteBool(Success);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += items_.CalculateSize(_repeated_items_codec);
      if (Success != false) {
        size += 1 + 1;
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LichSuPhanQuyenScopeListResponse other) {
      if (other == null) {
        return;
      }
      items_.Add(other.items_);
      if (other.Success != false) {
        Success = other.Success;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            items_.AddEntriesFrom(input, _repeated_items_codec);
            break;
          }
          case 16: {
            Success = input.ReadBool();
            break;
          }
          case 26: {
            Message = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            items_.AddEntriesFrom(ref input, _repeated_items_codec);
            break;
          }
          case 16: {
            Success = input.ReadBool();
            break;
          }
          case 26: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LichSuPhanQuyenScopeGetRequest : pb::IMessage<LichSuPhanQuyenScopeGetRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LichSuPhanQuyenScopeGetRequest> _parser = new pb::MessageParser<LichSuPhanQuyenScopeGetRequest>(() => new LichSuPhanQuyenScopeGetRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LichSuPhanQuyenScopeGetRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::protos.LichSuPhanQuyenScopeReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LichSuPhanQuyenScopeGetRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LichSuPhanQuyenScopeGetRequest(LichSuPhanQuyenScopeGetRequest other) : this() {
      id_ = other.id_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LichSuPhanQuyenScopeGetRequest Clone() {
      return new LichSuPhanQuyenScopeGetRequest(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LichSuPhanQuyenScopeGetRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LichSuPhanQuyenScopeGetRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LichSuPhanQuyenScopeGetRequest other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LichSuPhanQuyenScopeGetResponse : pb::IMessage<LichSuPhanQuyenScopeGetResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LichSuPhanQuyenScopeGetResponse> _parser = new pb::MessageParser<LichSuPhanQuyenScopeGetResponse>(() => new LichSuPhanQuyenScopeGetResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LichSuPhanQuyenScopeGetResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::protos.LichSuPhanQuyenScopeReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LichSuPhanQuyenScopeGetResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LichSuPhanQuyenScopeGetResponse(LichSuPhanQuyenScopeGetResponse other) : this() {
      item_ = other.item_ != null ? other.item_.Clone() : null;
      success_ = other.success_;
      message_ = other.message_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LichSuPhanQuyenScopeGetResponse Clone() {
      return new LichSuPhanQuyenScopeGetResponse(this);
    }

    /// <summary>Field number for the "item" field.</summary>
    public const int ItemFieldNumber = 1;
    private global::protos.LichSuPhanQuyenScope item_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::protos.LichSuPhanQuyenScope Item {
      get { return item_; }
      set {
        item_ = value;
      }
    }

    /// <summary>Field number for the "success" field.</summary>
    public const int SuccessFieldNumber = 2;
    private bool success_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Success {
      get { return success_; }
      set {
        success_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 3;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LichSuPhanQuyenScopeGetResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LichSuPhanQuyenScopeGetResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Item, other.Item)) return false;
      if (Success != other.Success) return false;
      if (Message != other.Message) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (item_ != null) hash ^= Item.GetHashCode();
      if (Success != false) hash ^= Success.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (item_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Item);
      }
      if (Success != false) {
        output.WriteRawTag(16);
        output.WriteBool(Success);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (item_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Item);
      }
      if (Success != false) {
        output.WriteRawTag(16);
        output.WriteBool(Success);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (item_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Item);
      }
      if (Success != false) {
        size += 1 + 1;
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LichSuPhanQuyenScopeGetResponse other) {
      if (other == null) {
        return;
      }
      if (other.item_ != null) {
        if (item_ == null) {
          Item = new global::protos.LichSuPhanQuyenScope();
        }
        Item.MergeFrom(other.Item);
      }
      if (other.Success != false) {
        Success = other.Success;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (item_ == null) {
              Item = new global::protos.LichSuPhanQuyenScope();
            }
            input.ReadMessage(Item);
            break;
          }
          case 16: {
            Success = input.ReadBool();
            break;
          }
          case 26: {
            Message = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (item_ == null) {
              Item = new global::protos.LichSuPhanQuyenScope();
            }
            input.ReadMessage(Item);
            break;
          }
          case 16: {
            Success = input.ReadBool();
            break;
          }
          case 26: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LichSuPhanQuyenScopeSaveRequest : pb::IMessage<LichSuPhanQuyenScopeSaveRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LichSuPhanQuyenScopeSaveRequest> _parser = new pb::MessageParser<LichSuPhanQuyenScopeSaveRequest>(() => new LichSuPhanQuyenScopeSaveRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LichSuPhanQuyenScopeSaveRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::protos.LichSuPhanQuyenScopeReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LichSuPhanQuyenScopeSaveRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LichSuPhanQuyenScopeSaveRequest(LichSuPhanQuyenScopeSaveRequest other) : this() {
      item_ = other.item_ != null ? other.item_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LichSuPhanQuyenScopeSaveRequest Clone() {
      return new LichSuPhanQuyenScopeSaveRequest(this);
    }

    /// <summary>Field number for the "item" field.</summary>
    public const int ItemFieldNumber = 1;
    private global::protos.LichSuPhanQuyenScope item_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::protos.LichSuPhanQuyenScope Item {
      get { return item_; }
      set {
        item_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LichSuPhanQuyenScopeSaveRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LichSuPhanQuyenScopeSaveRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Item, other.Item)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (item_ != null) hash ^= Item.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (item_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Item);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (item_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Item);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (item_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Item);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LichSuPhanQuyenScopeSaveRequest other) {
      if (other == null) {
        return;
      }
      if (other.item_ != null) {
        if (item_ == null) {
          Item = new global::protos.LichSuPhanQuyenScope();
        }
        Item.MergeFrom(other.Item);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (item_ == null) {
              Item = new global::protos.LichSuPhanQuyenScope();
            }
            input.ReadMessage(Item);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (item_ == null) {
              Item = new global::protos.LichSuPhanQuyenScope();
            }
            input.ReadMessage(Item);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class LichSuPhanQuyenScopeSaveResponse : pb::IMessage<LichSuPhanQuyenScopeSaveResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LichSuPhanQuyenScopeSaveResponse> _parser = new pb::MessageParser<LichSuPhanQuyenScopeSaveResponse>(() => new LichSuPhanQuyenScopeSaveResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LichSuPhanQuyenScopeSaveResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::protos.LichSuPhanQuyenScopeReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LichSuPhanQuyenScopeSaveResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LichSuPhanQuyenScopeSaveResponse(LichSuPhanQuyenScopeSaveResponse other) : this() {
      id_ = other.id_;
      success_ = other.success_;
      message_ = other.message_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LichSuPhanQuyenScopeSaveResponse Clone() {
      return new LichSuPhanQuyenScopeSaveResponse(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "success" field.</summary>
    public const int SuccessFieldNumber = 2;
    private bool success_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Success {
      get { return success_; }
      set {
        success_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 3;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LichSuPhanQuyenScopeSaveResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LichSuPhanQuyenScopeSaveResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Success != other.Success) return false;
      if (Message != other.Message) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Success != false) hash ^= Success.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Success != false) {
        output.WriteRawTag(16);
        output.WriteBool(Success);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Success != false) {
        output.WriteRawTag(16);
        output.WriteBool(Success);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Success != false) {
        size += 1 + 1;
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LichSuPhanQuyenScopeSaveResponse other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Success != false) {
        Success = other.Success;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 16: {
            Success = input.ReadBool();
            break;
          }
          case 26: {
            Message = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 16: {
            Success = input.ReadBool();
            break;
          }
          case 26: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
