// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: LichSuPhanQuyenScope.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace protos {
  public static partial class LichSuPhanQuyenScopeService
  {
    static readonly string __ServiceName = "LichSuPhanQuyenScope.LichSuPhanQuyenScopeService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.LichSuPhanQuyenScopeListRequest> __Marshaller_LichSuPhanQuyenScope_LichSuPhanQuyenScopeListRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.LichSuPhanQuyenScopeListRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.LichSuPhanQuyenScopeListResponse> __Marshaller_LichSuPhanQuyenScope_LichSuPhanQuyenScopeListResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.LichSuPhanQuyenScopeListResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.LichSuPhanQuyenScopeGetRequest> __Marshaller_LichSuPhanQuyenScope_LichSuPhanQuyenScopeGetRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.LichSuPhanQuyenScopeGetRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.LichSuPhanQuyenScopeGetResponse> __Marshaller_LichSuPhanQuyenScope_LichSuPhanQuyenScopeGetResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.LichSuPhanQuyenScopeGetResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.LichSuPhanQuyenScopeSaveRequest> __Marshaller_LichSuPhanQuyenScope_LichSuPhanQuyenScopeSaveRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.LichSuPhanQuyenScopeSaveRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.LichSuPhanQuyenScopeSaveResponse> __Marshaller_LichSuPhanQuyenScope_LichSuPhanQuyenScopeSaveResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.LichSuPhanQuyenScopeSaveResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.LichSuPhanQuyenScopeListRequest, global::protos.LichSuPhanQuyenScopeListResponse> __Method_GetList = new grpc::Method<global::protos.LichSuPhanQuyenScopeListRequest, global::protos.LichSuPhanQuyenScopeListResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetList",
        __Marshaller_LichSuPhanQuyenScope_LichSuPhanQuyenScopeListRequest,
        __Marshaller_LichSuPhanQuyenScope_LichSuPhanQuyenScopeListResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.LichSuPhanQuyenScopeGetRequest, global::protos.LichSuPhanQuyenScopeGetResponse> __Method_Get = new grpc::Method<global::protos.LichSuPhanQuyenScopeGetRequest, global::protos.LichSuPhanQuyenScopeGetResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Get",
        __Marshaller_LichSuPhanQuyenScope_LichSuPhanQuyenScopeGetRequest,
        __Marshaller_LichSuPhanQuyenScope_LichSuPhanQuyenScopeGetResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.LichSuPhanQuyenScopeSaveRequest, global::protos.LichSuPhanQuyenScopeSaveResponse> __Method_Save = new grpc::Method<global::protos.LichSuPhanQuyenScopeSaveRequest, global::protos.LichSuPhanQuyenScopeSaveResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Save",
        __Marshaller_LichSuPhanQuyenScope_LichSuPhanQuyenScopeSaveRequest,
        __Marshaller_LichSuPhanQuyenScope_LichSuPhanQuyenScopeSaveResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::protos.LichSuPhanQuyenScopeReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of LichSuPhanQuyenScopeService</summary>
    [grpc::BindServiceMethod(typeof(LichSuPhanQuyenScopeService), "BindService")]
    public abstract partial class LichSuPhanQuyenScopeServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.LichSuPhanQuyenScopeListResponse> GetList(global::protos.LichSuPhanQuyenScopeListRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.LichSuPhanQuyenScopeGetResponse> Get(global::protos.LichSuPhanQuyenScopeGetRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.LichSuPhanQuyenScopeSaveResponse> Save(global::protos.LichSuPhanQuyenScopeSaveRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(LichSuPhanQuyenScopeServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetList, serviceImpl.GetList)
          .AddMethod(__Method_Get, serviceImpl.Get)
          .AddMethod(__Method_Save, serviceImpl.Save).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, LichSuPhanQuyenScopeServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetList, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.LichSuPhanQuyenScopeListRequest, global::protos.LichSuPhanQuyenScopeListResponse>(serviceImpl.GetList));
      serviceBinder.AddMethod(__Method_Get, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.LichSuPhanQuyenScopeGetRequest, global::protos.LichSuPhanQuyenScopeGetResponse>(serviceImpl.Get));
      serviceBinder.AddMethod(__Method_Save, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.LichSuPhanQuyenScopeSaveRequest, global::protos.LichSuPhanQuyenScopeSaveResponse>(serviceImpl.Save));
    }

  }
}
#endregion
