// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: RelationshipObject.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace protos {
  public static partial class RelationShipObjectService
  {
    static readonly string __ServiceName = "RelationshipObject.RelationShipObjectService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.ListRelationShipObjectRequest> __Marshaller_RelationshipObject_ListRelationShipObjectRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.ListRelationShipObjectRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.ListRelationShipObjectResponse> __Marshaller_RelationshipObject_ListRelationShipObjectResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.ListRelationShipObjectResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.RelationShipObjectRequest> __Marshaller_RelationshipObject_RelationShipObjectRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.RelationShipObjectRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.RelationShipObjectResponse> __Marshaller_RelationshipObject_RelationShipObjectResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.RelationShipObjectResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.DeleteRelationShipObjectResponse> __Marshaller_RelationshipObject_DeleteRelationShipObjectResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.DeleteRelationShipObjectResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.SaveRelationShipObjectRequest> __Marshaller_RelationshipObject_SaveRelationShipObjectRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.SaveRelationShipObjectRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.SaveRelationShipObjectResponse> __Marshaller_RelationshipObject_SaveRelationShipObjectResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.SaveRelationShipObjectResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.ListRelationShipObjectRequest, global::protos.ListRelationShipObjectResponse> __Method_GetListRelationShipObject = new grpc::Method<global::protos.ListRelationShipObjectRequest, global::protos.ListRelationShipObjectResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetListRelationShipObject",
        __Marshaller_RelationshipObject_ListRelationShipObjectRequest,
        __Marshaller_RelationshipObject_ListRelationShipObjectResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.RelationShipObjectRequest, global::protos.RelationShipObjectResponse> __Method_GetRelationShipObject = new grpc::Method<global::protos.RelationShipObjectRequest, global::protos.RelationShipObjectResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetRelationShipObject",
        __Marshaller_RelationshipObject_RelationShipObjectRequest,
        __Marshaller_RelationshipObject_RelationShipObjectResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.RelationShipObjectRequest, global::protos.DeleteRelationShipObjectResponse> __Method_DeleteRelationShipObject = new grpc::Method<global::protos.RelationShipObjectRequest, global::protos.DeleteRelationShipObjectResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteRelationShipObject",
        __Marshaller_RelationshipObject_RelationShipObjectRequest,
        __Marshaller_RelationshipObject_DeleteRelationShipObjectResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.SaveRelationShipObjectRequest, global::protos.SaveRelationShipObjectResponse> __Method_SaveRelationShipObject = new grpc::Method<global::protos.SaveRelationShipObjectRequest, global::protos.SaveRelationShipObjectResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SaveRelationShipObject",
        __Marshaller_RelationshipObject_SaveRelationShipObjectRequest,
        __Marshaller_RelationshipObject_SaveRelationShipObjectResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::protos.RelationshipObjectReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of RelationShipObjectService</summary>
    [grpc::BindServiceMethod(typeof(RelationShipObjectService), "BindService")]
    public abstract partial class RelationShipObjectServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.ListRelationShipObjectResponse> GetListRelationShipObject(global::protos.ListRelationShipObjectRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.RelationShipObjectResponse> GetRelationShipObject(global::protos.RelationShipObjectRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.DeleteRelationShipObjectResponse> DeleteRelationShipObject(global::protos.RelationShipObjectRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.SaveRelationShipObjectResponse> SaveRelationShipObject(global::protos.SaveRelationShipObjectRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(RelationShipObjectServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetListRelationShipObject, serviceImpl.GetListRelationShipObject)
          .AddMethod(__Method_GetRelationShipObject, serviceImpl.GetRelationShipObject)
          .AddMethod(__Method_DeleteRelationShipObject, serviceImpl.DeleteRelationShipObject)
          .AddMethod(__Method_SaveRelationShipObject, serviceImpl.SaveRelationShipObject).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, RelationShipObjectServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetListRelationShipObject, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.ListRelationShipObjectRequest, global::protos.ListRelationShipObjectResponse>(serviceImpl.GetListRelationShipObject));
      serviceBinder.AddMethod(__Method_GetRelationShipObject, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.RelationShipObjectRequest, global::protos.RelationShipObjectResponse>(serviceImpl.GetRelationShipObject));
      serviceBinder.AddMethod(__Method_DeleteRelationShipObject, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.RelationShipObjectRequest, global::protos.DeleteRelationShipObjectResponse>(serviceImpl.DeleteRelationShipObject));
      serviceBinder.AddMethod(__Method_SaveRelationShipObject, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.SaveRelationShipObjectRequest, global::protos.SaveRelationShipObjectResponse>(serviceImpl.SaveRelationShipObject));
    }

  }
}
#endregion
