// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ThamSo.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace protos {
  /// <summary>
  /// ============================================================
  /// Service
  /// ============================================================
  /// </summary>
  public static partial class ThamSoService
  {
    static readonly string __ServiceName = "ThamSo.ThamSoService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.GetListDynamicFieldsRequest> __Marshaller_ThamSo_GetListDynamicFieldsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.GetListDynamicFieldsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.GetListDynamicFieldsResponse> __Marshaller_ThamSo_GetListDynamicFieldsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.GetListDynamicFieldsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.SaveDynamicFieldRequest> __Marshaller_ThamSo_SaveDynamicFieldRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.SaveDynamicFieldRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.SaveDynamicFieldResponse> __Marshaller_ThamSo_SaveDynamicFieldResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.SaveDynamicFieldResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.DeleteDynamicFieldRequest> __Marshaller_ThamSo_DeleteDynamicFieldRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.DeleteDynamicFieldRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.DeleteBaseResponse> __Marshaller_Base_DeleteBaseResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.DeleteBaseResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.RestoreDynamicFieldRequest> __Marshaller_ThamSo_RestoreDynamicFieldRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.RestoreDynamicFieldRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.StatusResponse> __Marshaller_Base_StatusResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.StatusResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.GetListFieldSetsRequest> __Marshaller_ThamSo_GetListFieldSetsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.GetListFieldSetsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.GetListFieldSetsResponse> __Marshaller_ThamSo_GetListFieldSetsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.GetListFieldSetsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.SaveFieldSetRequest> __Marshaller_ThamSo_SaveFieldSetRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.SaveFieldSetRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.SaveFieldSetResponse> __Marshaller_ThamSo_SaveFieldSetResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.SaveFieldSetResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.DeleteFieldSetRequest> __Marshaller_ThamSo_DeleteFieldSetRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.DeleteFieldSetRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.RestoreFieldSetRequest> __Marshaller_ThamSo_RestoreFieldSetRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.RestoreFieldSetRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.GetListFormConfigsRequest> __Marshaller_ThamSo_GetListFormConfigsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.GetListFormConfigsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.GetListFormConfigsResponse> __Marshaller_ThamSo_GetListFormConfigsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.GetListFormConfigsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.GetRuntimeFormSchemaRequest> __Marshaller_ThamSo_GetRuntimeFormSchemaRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.GetRuntimeFormSchemaRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.GetRuntimeFormSchemaResponse> __Marshaller_ThamSo_GetRuntimeFormSchemaResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.GetRuntimeFormSchemaResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.SaveFormConfigRequest> __Marshaller_ThamSo_SaveFormConfigRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.SaveFormConfigRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.SaveFormConfigResponse> __Marshaller_ThamSo_SaveFormConfigResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.SaveFormConfigResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.DeleteFormConfigRequest> __Marshaller_ThamSo_DeleteFormConfigRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.DeleteFormConfigRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.RestoreFormConfigRequest> __Marshaller_ThamSo_RestoreFormConfigRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.RestoreFormConfigRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.GetListDynamicMenusRequest> __Marshaller_ThamSo_GetListDynamicMenusRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.GetListDynamicMenusRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.GetListDynamicMenusResponse> __Marshaller_ThamSo_GetListDynamicMenusResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.GetListDynamicMenusResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.SaveDynamicMenuRequest> __Marshaller_ThamSo_SaveDynamicMenuRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.SaveDynamicMenuRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.SaveDynamicMenuResponse> __Marshaller_ThamSo_SaveDynamicMenuResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.SaveDynamicMenuResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.DeleteDynamicMenuRequest> __Marshaller_ThamSo_DeleteDynamicMenuRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.DeleteDynamicMenuRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.RestoreDynamicMenuRequest> __Marshaller_ThamSo_RestoreDynamicMenuRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.RestoreDynamicMenuRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.GetListDynamicMenuDataSourcesRequest> __Marshaller_ThamSo_GetListDynamicMenuDataSourcesRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.GetListDynamicMenuDataSourcesRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.GetListDynamicMenuDataSourcesResponse> __Marshaller_ThamSo_GetListDynamicMenuDataSourcesResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.GetListDynamicMenuDataSourcesResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.SaveDynamicMenuDataSourceRequest> __Marshaller_ThamSo_SaveDynamicMenuDataSourceRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.SaveDynamicMenuDataSourceRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.SaveDynamicMenuDataSourceResponse> __Marshaller_ThamSo_SaveDynamicMenuDataSourceResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.SaveDynamicMenuDataSourceResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.DeleteDynamicMenuDataSourceRequest> __Marshaller_ThamSo_DeleteDynamicMenuDataSourceRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.DeleteDynamicMenuDataSourceRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.RestoreDynamicMenuDataSourceRequest> __Marshaller_ThamSo_RestoreDynamicMenuDataSourceRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.RestoreDynamicMenuDataSourceRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.SyncDynamicMenuDataSourcesFromProtoRequest> __Marshaller_ThamSo_SyncDynamicMenuDataSourcesFromProtoRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.SyncDynamicMenuDataSourcesFromProtoRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.SyncDynamicMenuDataSourcesFromProtoResponse> __Marshaller_ThamSo_SyncDynamicMenuDataSourcesFromProtoResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.SyncDynamicMenuDataSourcesFromProtoResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.JobProgressEvent> __Marshaller_ThamSo_JobProgressEvent = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.JobProgressEvent.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.DiscoverCollectionFieldsRequest> __Marshaller_ThamSo_DiscoverCollectionFieldsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.DiscoverCollectionFieldsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.DiscoverCollectionFieldsResponse> __Marshaller_ThamSo_DiscoverCollectionFieldsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.DiscoverCollectionFieldsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.PreviewCollectionDocumentsRequest> __Marshaller_ThamSo_PreviewCollectionDocumentsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.PreviewCollectionDocumentsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.PreviewCollectionDocumentsResponse> __Marshaller_ThamSo_PreviewCollectionDocumentsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.PreviewCollectionDocumentsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.GetDynamicMenuRowsRequest> __Marshaller_ThamSo_GetDynamicMenuRowsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.GetDynamicMenuRowsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.GetDynamicMenuRowsResponse> __Marshaller_ThamSo_GetDynamicMenuRowsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.GetDynamicMenuRowsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.SaveDynamicMenuRowRequest> __Marshaller_ThamSo_SaveDynamicMenuRowRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.SaveDynamicMenuRowRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.SaveDynamicMenuRowResponse> __Marshaller_ThamSo_SaveDynamicMenuRowResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.SaveDynamicMenuRowResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.GetListTemplateLayoutSummariesRequest> __Marshaller_ThamSo_GetListTemplateLayoutSummariesRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.GetListTemplateLayoutSummariesRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.GetListTemplateLayoutSummariesResponse> __Marshaller_ThamSo_GetListTemplateLayoutSummariesResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.GetListTemplateLayoutSummariesResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.GetTemplateLayoutDetailRequest> __Marshaller_ThamSo_GetTemplateLayoutDetailRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.GetTemplateLayoutDetailRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.GetTemplateLayoutDetailResponse> __Marshaller_ThamSo_GetTemplateLayoutDetailResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.GetTemplateLayoutDetailResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.GetListTemplateLayoutsRequest> __Marshaller_ThamSo_GetListTemplateLayoutsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.GetListTemplateLayoutsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.GetListTemplateLayoutsResponse> __Marshaller_ThamSo_GetListTemplateLayoutsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.GetListTemplateLayoutsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.SaveTemplateLayoutRequest> __Marshaller_ThamSo_SaveTemplateLayoutRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.SaveTemplateLayoutRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.SaveTemplateLayoutResponse> __Marshaller_ThamSo_SaveTemplateLayoutResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.SaveTemplateLayoutResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.DeleteTemplateLayoutRequest> __Marshaller_ThamSo_DeleteTemplateLayoutRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.DeleteTemplateLayoutRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.RestoreTemplateLayoutRequest> __Marshaller_ThamSo_RestoreTemplateLayoutRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.RestoreTemplateLayoutRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::protos.ExportTemplateLayoutsRequest> __Marshaller_ThamSo_ExportTemplateLayoutsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::protos.ExportTemplateLayoutsRequest.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.GetListDynamicFieldsRequest, global::protos.GetListDynamicFieldsResponse> __Method_GetListDynamicFields = new grpc::Method<global::protos.GetListDynamicFieldsRequest, global::protos.GetListDynamicFieldsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetListDynamicFields",
        __Marshaller_ThamSo_GetListDynamicFieldsRequest,
        __Marshaller_ThamSo_GetListDynamicFieldsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.SaveDynamicFieldRequest, global::protos.SaveDynamicFieldResponse> __Method_SaveDynamicField = new grpc::Method<global::protos.SaveDynamicFieldRequest, global::protos.SaveDynamicFieldResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SaveDynamicField",
        __Marshaller_ThamSo_SaveDynamicFieldRequest,
        __Marshaller_ThamSo_SaveDynamicFieldResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.DeleteDynamicFieldRequest, global::protos.DeleteBaseResponse> __Method_DeleteDynamicField = new grpc::Method<global::protos.DeleteDynamicFieldRequest, global::protos.DeleteBaseResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteDynamicField",
        __Marshaller_ThamSo_DeleteDynamicFieldRequest,
        __Marshaller_Base_DeleteBaseResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.RestoreDynamicFieldRequest, global::protos.StatusResponse> __Method_RestoreDynamicField = new grpc::Method<global::protos.RestoreDynamicFieldRequest, global::protos.StatusResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RestoreDynamicField",
        __Marshaller_ThamSo_RestoreDynamicFieldRequest,
        __Marshaller_Base_StatusResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.DeleteDynamicFieldRequest, global::protos.DeleteBaseResponse> __Method_HardDeleteDynamicField = new grpc::Method<global::protos.DeleteDynamicFieldRequest, global::protos.DeleteBaseResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "HardDeleteDynamicField",
        __Marshaller_ThamSo_DeleteDynamicFieldRequest,
        __Marshaller_Base_DeleteBaseResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.GetListFieldSetsRequest, global::protos.GetListFieldSetsResponse> __Method_GetListFieldSets = new grpc::Method<global::protos.GetListFieldSetsRequest, global::protos.GetListFieldSetsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetListFieldSets",
        __Marshaller_ThamSo_GetListFieldSetsRequest,
        __Marshaller_ThamSo_GetListFieldSetsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.SaveFieldSetRequest, global::protos.SaveFieldSetResponse> __Method_SaveFieldSet = new grpc::Method<global::protos.SaveFieldSetRequest, global::protos.SaveFieldSetResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SaveFieldSet",
        __Marshaller_ThamSo_SaveFieldSetRequest,
        __Marshaller_ThamSo_SaveFieldSetResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.DeleteFieldSetRequest, global::protos.DeleteBaseResponse> __Method_DeleteFieldSet = new grpc::Method<global::protos.DeleteFieldSetRequest, global::protos.DeleteBaseResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteFieldSet",
        __Marshaller_ThamSo_DeleteFieldSetRequest,
        __Marshaller_Base_DeleteBaseResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.RestoreFieldSetRequest, global::protos.StatusResponse> __Method_RestoreFieldSet = new grpc::Method<global::protos.RestoreFieldSetRequest, global::protos.StatusResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RestoreFieldSet",
        __Marshaller_ThamSo_RestoreFieldSetRequest,
        __Marshaller_Base_StatusResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.GetListFormConfigsRequest, global::protos.GetListFormConfigsResponse> __Method_GetListFormConfigs = new grpc::Method<global::protos.GetListFormConfigsRequest, global::protos.GetListFormConfigsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetListFormConfigs",
        __Marshaller_ThamSo_GetListFormConfigsRequest,
        __Marshaller_ThamSo_GetListFormConfigsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.GetRuntimeFormSchemaRequest, global::protos.GetRuntimeFormSchemaResponse> __Method_GetRuntimeFormSchema = new grpc::Method<global::protos.GetRuntimeFormSchemaRequest, global::protos.GetRuntimeFormSchemaResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetRuntimeFormSchema",
        __Marshaller_ThamSo_GetRuntimeFormSchemaRequest,
        __Marshaller_ThamSo_GetRuntimeFormSchemaResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.SaveFormConfigRequest, global::protos.SaveFormConfigResponse> __Method_SaveFormConfig = new grpc::Method<global::protos.SaveFormConfigRequest, global::protos.SaveFormConfigResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SaveFormConfig",
        __Marshaller_ThamSo_SaveFormConfigRequest,
        __Marshaller_ThamSo_SaveFormConfigResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.DeleteFormConfigRequest, global::protos.DeleteBaseResponse> __Method_DeleteFormConfig = new grpc::Method<global::protos.DeleteFormConfigRequest, global::protos.DeleteBaseResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteFormConfig",
        __Marshaller_ThamSo_DeleteFormConfigRequest,
        __Marshaller_Base_DeleteBaseResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.RestoreFormConfigRequest, global::protos.StatusResponse> __Method_RestoreFormConfig = new grpc::Method<global::protos.RestoreFormConfigRequest, global::protos.StatusResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RestoreFormConfig",
        __Marshaller_ThamSo_RestoreFormConfigRequest,
        __Marshaller_Base_StatusResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.GetListDynamicMenusRequest, global::protos.GetListDynamicMenusResponse> __Method_GetListDynamicMenus = new grpc::Method<global::protos.GetListDynamicMenusRequest, global::protos.GetListDynamicMenusResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetListDynamicMenus",
        __Marshaller_ThamSo_GetListDynamicMenusRequest,
        __Marshaller_ThamSo_GetListDynamicMenusResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.SaveDynamicMenuRequest, global::protos.SaveDynamicMenuResponse> __Method_SaveDynamicMenu = new grpc::Method<global::protos.SaveDynamicMenuRequest, global::protos.SaveDynamicMenuResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SaveDynamicMenu",
        __Marshaller_ThamSo_SaveDynamicMenuRequest,
        __Marshaller_ThamSo_SaveDynamicMenuResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.DeleteDynamicMenuRequest, global::protos.DeleteBaseResponse> __Method_DeleteDynamicMenu = new grpc::Method<global::protos.DeleteDynamicMenuRequest, global::protos.DeleteBaseResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteDynamicMenu",
        __Marshaller_ThamSo_DeleteDynamicMenuRequest,
        __Marshaller_Base_DeleteBaseResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.RestoreDynamicMenuRequest, global::protos.StatusResponse> __Method_RestoreDynamicMenu = new grpc::Method<global::protos.RestoreDynamicMenuRequest, global::protos.StatusResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RestoreDynamicMenu",
        __Marshaller_ThamSo_RestoreDynamicMenuRequest,
        __Marshaller_Base_StatusResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.GetListDynamicMenuDataSourcesRequest, global::protos.GetListDynamicMenuDataSourcesResponse> __Method_GetListDynamicMenuDataSources = new grpc::Method<global::protos.GetListDynamicMenuDataSourcesRequest, global::protos.GetListDynamicMenuDataSourcesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetListDynamicMenuDataSources",
        __Marshaller_ThamSo_GetListDynamicMenuDataSourcesRequest,
        __Marshaller_ThamSo_GetListDynamicMenuDataSourcesResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.SaveDynamicMenuDataSourceRequest, global::protos.SaveDynamicMenuDataSourceResponse> __Method_SaveDynamicMenuDataSource = new grpc::Method<global::protos.SaveDynamicMenuDataSourceRequest, global::protos.SaveDynamicMenuDataSourceResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SaveDynamicMenuDataSource",
        __Marshaller_ThamSo_SaveDynamicMenuDataSourceRequest,
        __Marshaller_ThamSo_SaveDynamicMenuDataSourceResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.DeleteDynamicMenuDataSourceRequest, global::protos.DeleteBaseResponse> __Method_DeleteDynamicMenuDataSource = new grpc::Method<global::protos.DeleteDynamicMenuDataSourceRequest, global::protos.DeleteBaseResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteDynamicMenuDataSource",
        __Marshaller_ThamSo_DeleteDynamicMenuDataSourceRequest,
        __Marshaller_Base_DeleteBaseResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.RestoreDynamicMenuDataSourceRequest, global::protos.StatusResponse> __Method_RestoreDynamicMenuDataSource = new grpc::Method<global::protos.RestoreDynamicMenuDataSourceRequest, global::protos.StatusResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RestoreDynamicMenuDataSource",
        __Marshaller_ThamSo_RestoreDynamicMenuDataSourceRequest,
        __Marshaller_Base_StatusResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.SyncDynamicMenuDataSourcesFromProtoRequest, global::protos.SyncDynamicMenuDataSourcesFromProtoResponse> __Method_SyncDynamicMenuDataSourcesFromProto = new grpc::Method<global::protos.SyncDynamicMenuDataSourcesFromProtoRequest, global::protos.SyncDynamicMenuDataSourcesFromProtoResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SyncDynamicMenuDataSourcesFromProto",
        __Marshaller_ThamSo_SyncDynamicMenuDataSourcesFromProtoRequest,
        __Marshaller_ThamSo_SyncDynamicMenuDataSourcesFromProtoResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.SyncDynamicMenuDataSourcesFromProtoRequest, global::protos.JobProgressEvent> __Method_SyncDynamicMenuDataSourcesFromProtoStream = new grpc::Method<global::protos.SyncDynamicMenuDataSourcesFromProtoRequest, global::protos.JobProgressEvent>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "SyncDynamicMenuDataSourcesFromProtoStream",
        __Marshaller_ThamSo_SyncDynamicMenuDataSourcesFromProtoRequest,
        __Marshaller_ThamSo_JobProgressEvent);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.DiscoverCollectionFieldsRequest, global::protos.DiscoverCollectionFieldsResponse> __Method_DiscoverCollectionFields = new grpc::Method<global::protos.DiscoverCollectionFieldsRequest, global::protos.DiscoverCollectionFieldsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DiscoverCollectionFields",
        __Marshaller_ThamSo_DiscoverCollectionFieldsRequest,
        __Marshaller_ThamSo_DiscoverCollectionFieldsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.PreviewCollectionDocumentsRequest, global::protos.PreviewCollectionDocumentsResponse> __Method_PreviewCollectionDocuments = new grpc::Method<global::protos.PreviewCollectionDocumentsRequest, global::protos.PreviewCollectionDocumentsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "PreviewCollectionDocuments",
        __Marshaller_ThamSo_PreviewCollectionDocumentsRequest,
        __Marshaller_ThamSo_PreviewCollectionDocumentsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.GetDynamicMenuRowsRequest, global::protos.GetDynamicMenuRowsResponse> __Method_GetDynamicMenuRows = new grpc::Method<global::protos.GetDynamicMenuRowsRequest, global::protos.GetDynamicMenuRowsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetDynamicMenuRows",
        __Marshaller_ThamSo_GetDynamicMenuRowsRequest,
        __Marshaller_ThamSo_GetDynamicMenuRowsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.SaveDynamicMenuRowRequest, global::protos.SaveDynamicMenuRowResponse> __Method_SaveDynamicMenuRow = new grpc::Method<global::protos.SaveDynamicMenuRowRequest, global::protos.SaveDynamicMenuRowResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SaveDynamicMenuRow",
        __Marshaller_ThamSo_SaveDynamicMenuRowRequest,
        __Marshaller_ThamSo_SaveDynamicMenuRowResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.GetListTemplateLayoutSummariesRequest, global::protos.GetListTemplateLayoutSummariesResponse> __Method_GetListTemplateLayoutSummaries = new grpc::Method<global::protos.GetListTemplateLayoutSummariesRequest, global::protos.GetListTemplateLayoutSummariesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetListTemplateLayoutSummaries",
        __Marshaller_ThamSo_GetListTemplateLayoutSummariesRequest,
        __Marshaller_ThamSo_GetListTemplateLayoutSummariesResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.GetTemplateLayoutDetailRequest, global::protos.GetTemplateLayoutDetailResponse> __Method_GetTemplateLayoutDetail = new grpc::Method<global::protos.GetTemplateLayoutDetailRequest, global::protos.GetTemplateLayoutDetailResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetTemplateLayoutDetail",
        __Marshaller_ThamSo_GetTemplateLayoutDetailRequest,
        __Marshaller_ThamSo_GetTemplateLayoutDetailResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.GetListTemplateLayoutsRequest, global::protos.GetListTemplateLayoutsResponse> __Method_GetListTemplateLayouts = new grpc::Method<global::protos.GetListTemplateLayoutsRequest, global::protos.GetListTemplateLayoutsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetListTemplateLayouts",
        __Marshaller_ThamSo_GetListTemplateLayoutsRequest,
        __Marshaller_ThamSo_GetListTemplateLayoutsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.SaveTemplateLayoutRequest, global::protos.SaveTemplateLayoutResponse> __Method_SaveTemplateLayout = new grpc::Method<global::protos.SaveTemplateLayoutRequest, global::protos.SaveTemplateLayoutResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SaveTemplateLayout",
        __Marshaller_ThamSo_SaveTemplateLayoutRequest,
        __Marshaller_ThamSo_SaveTemplateLayoutResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.DeleteTemplateLayoutRequest, global::protos.DeleteBaseResponse> __Method_DeleteTemplateLayout = new grpc::Method<global::protos.DeleteTemplateLayoutRequest, global::protos.DeleteBaseResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteTemplateLayout",
        __Marshaller_ThamSo_DeleteTemplateLayoutRequest,
        __Marshaller_Base_DeleteBaseResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.RestoreTemplateLayoutRequest, global::protos.StatusResponse> __Method_RestoreTemplateLayout = new grpc::Method<global::protos.RestoreTemplateLayoutRequest, global::protos.StatusResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RestoreTemplateLayout",
        __Marshaller_ThamSo_RestoreTemplateLayoutRequest,
        __Marshaller_Base_StatusResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::protos.ExportTemplateLayoutsRequest, global::protos.JobProgressEvent> __Method_ExportTemplateLayoutsStream = new grpc::Method<global::protos.ExportTemplateLayoutsRequest, global::protos.JobProgressEvent>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "ExportTemplateLayoutsStream",
        __Marshaller_ThamSo_ExportTemplateLayoutsRequest,
        __Marshaller_ThamSo_JobProgressEvent);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::protos.ThamSoReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ThamSoService</summary>
    [grpc::BindServiceMethod(typeof(ThamSoService), "BindService")]
    public abstract partial class ThamSoServiceBase
    {
      /// <summary>
      /// DynamicField
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.GetListDynamicFieldsResponse> GetListDynamicFields(global::protos.GetListDynamicFieldsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.SaveDynamicFieldResponse> SaveDynamicField(global::protos.SaveDynamicFieldRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.DeleteBaseResponse> DeleteDynamicField(global::protos.DeleteDynamicFieldRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.StatusResponse> RestoreDynamicField(global::protos.RestoreDynamicFieldRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.DeleteBaseResponse> HardDeleteDynamicField(global::protos.DeleteDynamicFieldRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// FieldSet
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.GetListFieldSetsResponse> GetListFieldSets(global::protos.GetListFieldSetsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.SaveFieldSetResponse> SaveFieldSet(global::protos.SaveFieldSetRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.DeleteBaseResponse> DeleteFieldSet(global::protos.DeleteFieldSetRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.StatusResponse> RestoreFieldSet(global::protos.RestoreFieldSetRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// FormConfig
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.GetListFormConfigsResponse> GetListFormConfigs(global::protos.GetListFormConfigsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.GetRuntimeFormSchemaResponse> GetRuntimeFormSchema(global::protos.GetRuntimeFormSchemaRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.SaveFormConfigResponse> SaveFormConfig(global::protos.SaveFormConfigRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.DeleteBaseResponse> DeleteFormConfig(global::protos.DeleteFormConfigRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.StatusResponse> RestoreFormConfig(global::protos.RestoreFormConfigRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// DynamicMenu
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.GetListDynamicMenusResponse> GetListDynamicMenus(global::protos.GetListDynamicMenusRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.SaveDynamicMenuResponse> SaveDynamicMenu(global::protos.SaveDynamicMenuRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.DeleteBaseResponse> DeleteDynamicMenu(global::protos.DeleteDynamicMenuRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.StatusResponse> RestoreDynamicMenu(global::protos.RestoreDynamicMenuRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// DynamicMenu datasource registry
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.GetListDynamicMenuDataSourcesResponse> GetListDynamicMenuDataSources(global::protos.GetListDynamicMenuDataSourcesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.SaveDynamicMenuDataSourceResponse> SaveDynamicMenuDataSource(global::protos.SaveDynamicMenuDataSourceRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.DeleteBaseResponse> DeleteDynamicMenuDataSource(global::protos.DeleteDynamicMenuDataSourceRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.StatusResponse> RestoreDynamicMenuDataSource(global::protos.RestoreDynamicMenuDataSourceRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.SyncDynamicMenuDataSourcesFromProtoResponse> SyncDynamicMenuDataSourcesFromProto(global::protos.SyncDynamicMenuDataSourcesFromProtoRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task SyncDynamicMenuDataSourcesFromProtoStream(global::protos.SyncDynamicMenuDataSourcesFromProtoRequest request, grpc::IServerStreamWriter<global::protos.JobProgressEvent> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.DiscoverCollectionFieldsResponse> DiscoverCollectionFields(global::protos.DiscoverCollectionFieldsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.PreviewCollectionDocumentsResponse> PreviewCollectionDocuments(global::protos.PreviewCollectionDocumentsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.GetDynamicMenuRowsResponse> GetDynamicMenuRows(global::protos.GetDynamicMenuRowsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.SaveDynamicMenuRowResponse> SaveDynamicMenuRow(global::protos.SaveDynamicMenuRowRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Puck template layout
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.GetListTemplateLayoutSummariesResponse> GetListTemplateLayoutSummaries(global::protos.GetListTemplateLayoutSummariesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.GetTemplateLayoutDetailResponse> GetTemplateLayoutDetail(global::protos.GetTemplateLayoutDetailRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.GetListTemplateLayoutsResponse> GetListTemplateLayouts(global::protos.GetListTemplateLayoutsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.SaveTemplateLayoutResponse> SaveTemplateLayout(global::protos.SaveTemplateLayoutRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.DeleteBaseResponse> DeleteTemplateLayout(global::protos.DeleteTemplateLayoutRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::protos.StatusResponse> RestoreTemplateLayout(global::protos.RestoreTemplateLayoutRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task ExportTemplateLayoutsStream(global::protos.ExportTemplateLayoutsRequest request, grpc::IServerStreamWriter<global::protos.JobProgressEvent> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(ThamSoServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetListDynamicFields, serviceImpl.GetListDynamicFields)
          .AddMethod(__Method_SaveDynamicField, serviceImpl.SaveDynamicField)
          .AddMethod(__Method_DeleteDynamicField, serviceImpl.DeleteDynamicField)
          .AddMethod(__Method_RestoreDynamicField, serviceImpl.RestoreDynamicField)
          .AddMethod(__Method_HardDeleteDynamicField, serviceImpl.HardDeleteDynamicField)
          .AddMethod(__Method_GetListFieldSets, serviceImpl.GetListFieldSets)
          .AddMethod(__Method_SaveFieldSet, serviceImpl.SaveFieldSet)
          .AddMethod(__Method_DeleteFieldSet, serviceImpl.DeleteFieldSet)
          .AddMethod(__Method_RestoreFieldSet, serviceImpl.RestoreFieldSet)
          .AddMethod(__Method_GetListFormConfigs, serviceImpl.GetListFormConfigs)
          .AddMethod(__Method_GetRuntimeFormSchema, serviceImpl.GetRuntimeFormSchema)
          .AddMethod(__Method_SaveFormConfig, serviceImpl.SaveFormConfig)
          .AddMethod(__Method_DeleteFormConfig, serviceImpl.DeleteFormConfig)
          .AddMethod(__Method_RestoreFormConfig, serviceImpl.RestoreFormConfig)
          .AddMethod(__Method_GetListDynamicMenus, serviceImpl.GetListDynamicMenus)
          .AddMethod(__Method_SaveDynamicMenu, serviceImpl.SaveDynamicMenu)
          .AddMethod(__Method_DeleteDynamicMenu, serviceImpl.DeleteDynamicMenu)
          .AddMethod(__Method_RestoreDynamicMenu, serviceImpl.RestoreDynamicMenu)
          .AddMethod(__Method_GetListDynamicMenuDataSources, serviceImpl.GetListDynamicMenuDataSources)
          .AddMethod(__Method_SaveDynamicMenuDataSource, serviceImpl.SaveDynamicMenuDataSource)
          .AddMethod(__Method_DeleteDynamicMenuDataSource, serviceImpl.DeleteDynamicMenuDataSource)
          .AddMethod(__Method_RestoreDynamicMenuDataSource, serviceImpl.RestoreDynamicMenuDataSource)
          .AddMethod(__Method_SyncDynamicMenuDataSourcesFromProto, serviceImpl.SyncDynamicMenuDataSourcesFromProto)
          .AddMethod(__Method_SyncDynamicMenuDataSourcesFromProtoStream, serviceImpl.SyncDynamicMenuDataSourcesFromProtoStream)
          .AddMethod(__Method_DiscoverCollectionFields, serviceImpl.DiscoverCollectionFields)
          .AddMethod(__Method_PreviewCollectionDocuments, serviceImpl.PreviewCollectionDocuments)
          .AddMethod(__Method_GetDynamicMenuRows, serviceImpl.GetDynamicMenuRows)
          .AddMethod(__Method_SaveDynamicMenuRow, serviceImpl.SaveDynamicMenuRow)
          .AddMethod(__Method_GetListTemplateLayoutSummaries, serviceImpl.GetListTemplateLayoutSummaries)
          .AddMethod(__Method_GetTemplateLayoutDetail, serviceImpl.GetTemplateLayoutDetail)
          .AddMethod(__Method_GetListTemplateLayouts, serviceImpl.GetListTemplateLayouts)
          .AddMethod(__Method_SaveTemplateLayout, serviceImpl.SaveTemplateLayout)
          .AddMethod(__Method_DeleteTemplateLayout, serviceImpl.DeleteTemplateLayout)
          .AddMethod(__Method_RestoreTemplateLayout, serviceImpl.RestoreTemplateLayout)
          .AddMethod(__Method_ExportTemplateLayoutsStream, serviceImpl.ExportTemplateLayoutsStream).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ThamSoServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetListDynamicFields, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.GetListDynamicFieldsRequest, global::protos.GetListDynamicFieldsResponse>(serviceImpl.GetListDynamicFields));
      serviceBinder.AddMethod(__Method_SaveDynamicField, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.SaveDynamicFieldRequest, global::protos.SaveDynamicFieldResponse>(serviceImpl.SaveDynamicField));
      serviceBinder.AddMethod(__Method_DeleteDynamicField, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.DeleteDynamicFieldRequest, global::protos.DeleteBaseResponse>(serviceImpl.DeleteDynamicField));
      serviceBinder.AddMethod(__Method_RestoreDynamicField, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.RestoreDynamicFieldRequest, global::protos.StatusResponse>(serviceImpl.RestoreDynamicField));
      serviceBinder.AddMethod(__Method_HardDeleteDynamicField, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.DeleteDynamicFieldRequest, global::protos.DeleteBaseResponse>(serviceImpl.HardDeleteDynamicField));
      serviceBinder.AddMethod(__Method_GetListFieldSets, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.GetListFieldSetsRequest, global::protos.GetListFieldSetsResponse>(serviceImpl.GetListFieldSets));
      serviceBinder.AddMethod(__Method_SaveFieldSet, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.SaveFieldSetRequest, global::protos.SaveFieldSetResponse>(serviceImpl.SaveFieldSet));
      serviceBinder.AddMethod(__Method_DeleteFieldSet, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.DeleteFieldSetRequest, global::protos.DeleteBaseResponse>(serviceImpl.DeleteFieldSet));
      serviceBinder.AddMethod(__Method_RestoreFieldSet, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.RestoreFieldSetRequest, global::protos.StatusResponse>(serviceImpl.RestoreFieldSet));
      serviceBinder.AddMethod(__Method_GetListFormConfigs, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.GetListFormConfigsRequest, global::protos.GetListFormConfigsResponse>(serviceImpl.GetListFormConfigs));
      serviceBinder.AddMethod(__Method_GetRuntimeFormSchema, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.GetRuntimeFormSchemaRequest, global::protos.GetRuntimeFormSchemaResponse>(serviceImpl.GetRuntimeFormSchema));
      serviceBinder.AddMethod(__Method_SaveFormConfig, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.SaveFormConfigRequest, global::protos.SaveFormConfigResponse>(serviceImpl.SaveFormConfig));
      serviceBinder.AddMethod(__Method_DeleteFormConfig, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.DeleteFormConfigRequest, global::protos.DeleteBaseResponse>(serviceImpl.DeleteFormConfig));
      serviceBinder.AddMethod(__Method_RestoreFormConfig, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.RestoreFormConfigRequest, global::protos.StatusResponse>(serviceImpl.RestoreFormConfig));
      serviceBinder.AddMethod(__Method_GetListDynamicMenus, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.GetListDynamicMenusRequest, global::protos.GetListDynamicMenusResponse>(serviceImpl.GetListDynamicMenus));
      serviceBinder.AddMethod(__Method_SaveDynamicMenu, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.SaveDynamicMenuRequest, global::protos.SaveDynamicMenuResponse>(serviceImpl.SaveDynamicMenu));
      serviceBinder.AddMethod(__Method_DeleteDynamicMenu, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.DeleteDynamicMenuRequest, global::protos.DeleteBaseResponse>(serviceImpl.DeleteDynamicMenu));
      serviceBinder.AddMethod(__Method_RestoreDynamicMenu, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.RestoreDynamicMenuRequest, global::protos.StatusResponse>(serviceImpl.RestoreDynamicMenu));
      serviceBinder.AddMethod(__Method_GetListDynamicMenuDataSources, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.GetListDynamicMenuDataSourcesRequest, global::protos.GetListDynamicMenuDataSourcesResponse>(serviceImpl.GetListDynamicMenuDataSources));
      serviceBinder.AddMethod(__Method_SaveDynamicMenuDataSource, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.SaveDynamicMenuDataSourceRequest, global::protos.SaveDynamicMenuDataSourceResponse>(serviceImpl.SaveDynamicMenuDataSource));
      serviceBinder.AddMethod(__Method_DeleteDynamicMenuDataSource, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.DeleteDynamicMenuDataSourceRequest, global::protos.DeleteBaseResponse>(serviceImpl.DeleteDynamicMenuDataSource));
      serviceBinder.AddMethod(__Method_RestoreDynamicMenuDataSource, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.RestoreDynamicMenuDataSourceRequest, global::protos.StatusResponse>(serviceImpl.RestoreDynamicMenuDataSource));
      serviceBinder.AddMethod(__Method_SyncDynamicMenuDataSourcesFromProto, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.SyncDynamicMenuDataSourcesFromProtoRequest, global::protos.SyncDynamicMenuDataSourcesFromProtoResponse>(serviceImpl.SyncDynamicMenuDataSourcesFromProto));
      serviceBinder.AddMethod(__Method_SyncDynamicMenuDataSourcesFromProtoStream, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::protos.SyncDynamicMenuDataSourcesFromProtoRequest, global::protos.JobProgressEvent>(serviceImpl.SyncDynamicMenuDataSourcesFromProtoStream));
      serviceBinder.AddMethod(__Method_DiscoverCollectionFields, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.DiscoverCollectionFieldsRequest, global::protos.DiscoverCollectionFieldsResponse>(serviceImpl.DiscoverCollectionFields));
      serviceBinder.AddMethod(__Method_PreviewCollectionDocuments, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.PreviewCollectionDocumentsRequest, global::protos.PreviewCollectionDocumentsResponse>(serviceImpl.PreviewCollectionDocuments));
      serviceBinder.AddMethod(__Method_GetDynamicMenuRows, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.GetDynamicMenuRowsRequest, global::protos.GetDynamicMenuRowsResponse>(serviceImpl.GetDynamicMenuRows));
      serviceBinder.AddMethod(__Method_SaveDynamicMenuRow, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.SaveDynamicMenuRowRequest, global::protos.SaveDynamicMenuRowResponse>(serviceImpl.SaveDynamicMenuRow));
      serviceBinder.AddMethod(__Method_GetListTemplateLayoutSummaries, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.GetListTemplateLayoutSummariesRequest, global::protos.GetListTemplateLayoutSummariesResponse>(serviceImpl.GetListTemplateLayoutSummaries));
      serviceBinder.AddMethod(__Method_GetTemplateLayoutDetail, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.GetTemplateLayoutDetailRequest, global::protos.GetTemplateLayoutDetailResponse>(serviceImpl.GetTemplateLayoutDetail));
      serviceBinder.AddMethod(__Method_GetListTemplateLayouts, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.GetListTemplateLayoutsRequest, global::protos.GetListTemplateLayoutsResponse>(serviceImpl.GetListTemplateLayouts));
      serviceBinder.AddMethod(__Method_SaveTemplateLayout, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.SaveTemplateLayoutRequest, global::protos.SaveTemplateLayoutResponse>(serviceImpl.SaveTemplateLayout));
      serviceBinder.AddMethod(__Method_DeleteTemplateLayout, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.DeleteTemplateLayoutRequest, global::protos.DeleteBaseResponse>(serviceImpl.DeleteTemplateLayout));
      serviceBinder.AddMethod(__Method_RestoreTemplateLayout, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::protos.RestoreTemplateLayoutRequest, global::protos.StatusResponse>(serviceImpl.RestoreTemplateLayout));
      serviceBinder.AddMethod(__Method_ExportTemplateLayoutsStream, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::protos.ExportTemplateLayoutsRequest, global::protos.JobProgressEvent>(serviceImpl.ExportTemplateLayoutsStream));
    }

  }
}
#endregion
